// Code generated by command: go run gen.go -out kernels_amd64.s -stubs kernels_stubs_amd64.go -pkg bcn. DO NOT EDIT.

//go:build amd64 && !purego

package bcn

// findMinMaxSSE2 computes per-channel min/max over 16 RGBA pixels.
// Returns min RGBA packed little-endian in the low 32 bits and max RGBA in the high 32 bits.
//
//go:noescape
func findMinMaxSSE2(block *[64]byte) uint64

// decodeDXT1RowAVX2 decodes n consecutive interior DXT1 blocks (8 bytes each)
// into dst as 4 NRGBA rows of 16 bytes spaced stride bytes apart.
//
//go:noescape
func decodeDXT1RowAVX2(dst *byte, src *byte, n int, stride int)

// decodeDXT5RowAVX2 decodes n consecutive interior DXT5 blocks (16 bytes each)
// into dst as 4 NRGBA rows of 16 bytes spaced stride bytes apart. Requires BMI2.
//
//go:noescape
func decodeDXT5RowAVX2(dst *byte, src *byte, n int, stride int)

// decodeBC4RowAVX2 decodes n consecutive interior BC4 blocks (8 bytes each)
// into dst as 4 gray NRGBA rows spaced stride bytes apart. Requires BMI2.
//
//go:noescape
func decodeBC4RowAVX2(dst *byte, src *byte, n int, stride int)

// decodeBC5RowAVX2 decodes n consecutive interior BC5 blocks (16 bytes each)
// into dst as 4 NRGBA rows (R, G, 0, 255) spaced stride bytes apart. Requires BMI2.
//
//go:noescape
func decodeBC5RowAVX2(dst *byte, src *byte, n int, stride int)

// packDXT1IndicesAVX2 maps 16 NRGBA pixels to weighted-SSE-nearest palette
// entries and packs the 2-bit indices. Alpha mode is driven by the params
// block: a sub-threshold pixel is forced to index 3 and the entry-3 penalty
// keeps that entry from winning the argmin. Ties keep the lowest index.
//
//go:noescape
func packDXT1IndicesAVX2(block *[64]byte, params *[20]int32) uint32

// scoreDXT1PaletteAVX2 returns the total weighted block error of one BC1
// endpoint pair (cc = c0 | c1<<16) over 16 pixels, palette built like the
// Go encoder. Used to drive endpoint refinement.
//
//go:noescape
func scoreDXT1PaletteAVX2(block *[64]byte, cc uint32, weights *[4]int32) uint32

// alphaBlockErrorAVX2 returns the summed minimum squared error of 16 alpha
// samples against an 8-entry palette (BC3/BC4 alpha block scoring).
//
//go:noescape
func alphaBlockErrorAVX2(samples *[16]uint8, palette *[8]int32) uint32

// bestAlphaIndices16AVX2 returns the packed 48-bit BC3/BC4 alpha indices
// for 16 samples against an 8-entry palette. Ties keep the lowest index.
//
//go:noescape
func bestAlphaIndices16AVX2(samples *[16]uint8, palette *[8]int32) uint64
