// Code generated by command: go run gen.go -out kernels_amd64.s -stubs kernels_stubs_amd64.go -pkg bcn. DO NOT EDIT.

//go:build amd64 && !purego

package bcn

// findMinMaxSSE2 computes per-channel min/max over 16 RGBA pixels.
// Returns min RGBA packed little-endian in the low 32 bits and max RGBA in the high 32 bits.
//
//go:noescape
func findMinMaxSSE2(block *[64]byte) uint64
