// Code generated by command: go run gen.go -out kernels_amd64.s -stubs kernels_stubs_amd64.go -pkg bcn. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func findMinMaxSSE2(block *[64]byte) uint64
// Requires: SSE2
TEXT ·findMinMaxSSE2(SB), NOSPLIT, $0-16
	MOVQ      block+0(FP), AX
	MOVOU     (AX), X0
	MOVOU     16(AX), X1
	MOVOU     32(AX), X2
	MOVOU     48(AX), X3
	MOVOU     X0, X4
	PMINUB    X1, X4
	PMAXUB    X1, X0
	PMINUB    X2, X4
	PMAXUB    X2, X0
	PMINUB    X3, X4
	PMAXUB    X3, X0
	PSHUFD    $0x4e, X4, X1
	PMINUB    X1, X4
	PSHUFD    $0xe5, X4, X1
	PMINUB    X1, X4
	PSHUFD    $0x4e, X0, X1
	PMAXUB    X1, X0
	PSHUFD    $0xe5, X0, X1
	PMAXUB    X1, X0
	PUNPCKLLQ X0, X4
	MOVQ      X4, AX
	MOVQ      AX, ret+8(FP)
	RET
