// Code generated by command: go run gen.go -out kernels_amd64.s -stubs kernels_stubs_amd64.go -pkg bcn. DO NOT EDIT.

//go:build amd64 && !purego

package bcn

// findMinMaxSSE2 computes per-channel min/max over 16 RGBA pixels.
// Returns min RGBA packed little-endian in the low 32 bits and max RGBA in the high 32 bits.
//
//go:noescape
func findMinMaxSSE2(block *[64]byte) uint64

// decodeDXT1RowAVX2 decodes n consecutive interior DXT1 blocks (8 bytes each)
// into dst as 4 NRGBA rows of 16 bytes spaced stride bytes apart.
//
//go:noescape
func decodeDXT1RowAVX2(dst *byte, src *byte, n int, stride int)

// decodeDXT5RowAVX2 decodes n consecutive interior DXT5 blocks (16 bytes each)
// into dst as 4 NRGBA rows of 16 bytes spaced stride bytes apart. Requires BMI2.
//
//go:noescape
func decodeDXT5RowAVX2(dst *byte, src *byte, n int, stride int)

// decodeBC4RowAVX2 decodes n consecutive interior BC4 blocks (8 bytes each)
// into dst as 4 gray NRGBA rows spaced stride bytes apart. Requires BMI2.
//
//go:noescape
func decodeBC4RowAVX2(dst *byte, src *byte, n int, stride int)

// decodeBC5RowAVX2 decodes n consecutive interior BC5 blocks (16 bytes each)
// into dst as 4 NRGBA rows (R, G, 0, 255) spaced stride bytes apart. Requires BMI2.
//
//go:noescape
func decodeBC5RowAVX2(dst *byte, src *byte, n int, stride int)
