// SPDX-License-Identifier: MIT
// Copyright (c) 2026 WoozyMasta
// Source: github.com/woozymasta/bcn

// Package simd provides the amd64 SIMD (AVX2/SSE2, BMI2) assembly kernels used
// by the bcn encoder/decoder, together with runtime CPU feature flags. The
// kernels operate on primitive types only; the type-aware dispatch and the
// pure-Go fallbacks live in the parent bcn package. Assembly is generated by
// the build-time-only module in ./asmgen (see `make generate`).
package simd
