// Code generated by command: go run gen.go -out ../kernels_amd64.s -stubs ../kernels_stubs_amd64.go -pkg simd. DO NOT EDIT.

//go:build amd64 && !purego

package simd

// FindMinMaxSSE2 computes per-channel min/max over 16 RGBA pixels.
// Returns min RGBA packed little-endian in the low 32 bits and max RGBA in the high 32 bits.
//
//go:noescape
func FindMinMaxSSE2(block *[64]byte) uint64

// DecodeBC1RowAVX2 decodes n consecutive interior BC1 blocks (8 bytes each)
// into dst as 4 NRGBA rows of 16 bytes spaced stride bytes apart.
//
//go:noescape
func DecodeBC1RowAVX2(dst *byte, src *byte, n int, stride int)

// DecodeBC2RowAVX2 decodes n consecutive interior BC2 blocks (16 bytes each)
// into dst as 4 NRGBA rows of 16 bytes spaced stride bytes apart. Requires BMI2.
//
//go:noescape
func DecodeBC2RowAVX2(dst *byte, src *byte, n int, stride int)

// DecodeBC3RowAVX2 decodes n consecutive interior BC3 blocks (16 bytes each)
// into dst as 4 NRGBA rows of 16 bytes spaced stride bytes apart. Requires BMI2.
//
//go:noescape
func DecodeBC3RowAVX2(dst *byte, src *byte, n int, stride int)

// DecodeBC4RowAVX2 decodes n consecutive interior BC4 blocks (8 bytes each)
// into dst as 4 gray NRGBA rows spaced stride bytes apart. Requires BMI2.
//
//go:noescape
func DecodeBC4RowAVX2(dst *byte, src *byte, n int, stride int)

// DecodeBC5RowAVX2 decodes n consecutive interior BC5 blocks (16 bytes each)
// into dst as 4 NRGBA rows (R, G, 0, 255) spaced stride bytes apart. Requires BMI2.
//
//go:noescape
func DecodeBC5RowAVX2(dst *byte, src *byte, n int, stride int)

// PackBC1IndicesAVX2 maps 16 NRGBA pixels to weighted-SSE-nearest palette entries
// and packs the 2-bit indices. Alpha mode is driven by the params block:
// a sub-threshold pixel is forced to index 3 and the entry-3 penalty keeps that entry from winning the argmin.
// Ties keep the lowest index.
//
//go:noescape
func PackBC1IndicesAVX2(block *[64]byte, params *[20]int32) uint32

// ScoreBC1PaletteAVX2 returns the total weighted block error of one BC1 endpoint pair
// (cc = c0 | c1<<16) over 16 pixels, palette built like the Go encoder.
// Used to drive endpoint refinement.
//
//go:noescape
func ScoreBC1PaletteAVX2(block *[64]byte, cc uint32, weights *[4]int32) uint32

// BC7Mode6IndicesAVX2 assigns 16 RGBA pixels to the nearest mode 6 palette entry.
// params stores palette channels as 16 R, 16 G, 16 B, 16 A int32 values.
//
//go:noescape
func BC7Mode6IndicesAVX2(block *[64]byte, params *[64]int32, idx *[16]int32) uint32

// BC7SubsetEvalAVX2 assigns nearest RGB palette indices for one subset
// and accumulates least-squares sums {aa,bb,ab,aR,aG,aB,bR,bG,bB} plus the total error in out[9].
// Texels outside the subset (part&3 != subset) are ignored.
//
//go:noescape
func BC7SubsetEvalAVX2(block *[64]byte, part *[16]byte, params *[34]int32, out *[10]int32)

// BC7Mode7SubsetEvalAVX2 assigns nearest RGBA palette indices for one subset
// and accumulates least-squares sums {aa,bb,ab,aR,aG,aB,aA,bR,bG,bB,bA} plus the total error in out[11].
// Texels outside the subset are ignored.
//
//go:noescape
func BC7Mode7SubsetEvalAVX2(block *[64]byte, part *[16]byte, params *[22]int32, out *[12]int32)

// BC6HFindIndices1SubAVX2 assigns 16 BC6H texels to the nearest of 16 palette entries.
// block and pal use SOA layout: R[16], G[16], B[16] as int32 (192 bytes each).
// idx receives the winning palette index per texel as int32; caller narrows to byte.
// Distance metric is L1 (Manhattan): |dr|+|dg|+|db|, matching bc6hFindIndices1SubGo.
//
//go:noescape
func BC6HFindIndices1SubAVX2(block *[48]int32, pal *[48]int32, idx *[16]int32)

// BC6HFindIndices2SubAVX2 assigns BC6H texels of one subset to the nearest of 8 palette entries.
// block uses SOA layout: R[16], G[16], B[16] as int32 (192 bytes).
// pal uses SOA layout: R[8], G[8], B[8] as int32 (96 bytes).
// part[i]&1 must equal subset for texel i to be assigned; non-subset texels get idx[i]=0.
// Distance metric is L1 (Manhattan): |dr|+|dg|+|db|, matching bc6hFindIndices2SubGo.
//
//go:noescape
func BC6HFindIndices2SubAVX2(block *[48]int32, pal *[24]int32, part *[16]byte, subset int32, idx *[16]int32)

// AlphaBlockErrorAVX2 returns the summed minimum squared error of 16 alpha samples
// against the palette of endpoints aa = a0 | a1<<8 (BC3/BC4 scoring).
//
//go:noescape
func AlphaBlockErrorAVX2(samples *[16]uint8, aa uint32) uint32

// BestAlphaIndices16AVX2 returns the packed 48-bit BC3/BC4 alpha indices
// for 16 samples against the palette of endpoints aa = a0 | a1<<8.
// Ties keep the lowest index.
//
//go:noescape
func BestAlphaIndices16AVX2(samples *[16]uint8, aa uint32) uint64

// LSQColorAccumulateAVX2 assigns BC1 palette indices and accumulates
// least-squares normal-equation sums for 16 RGBA pixels.
//
//go:noescape
func LSQColorAccumulateAVX2(block *[64]byte, params *[22]int32, out *[9]int32)

// LSQAlphaAccumulateAVX2 assigns BC3/BC4 alpha indices and accumulates
// least-squares normal-equation sums for 16 samples.
//
//go:noescape
func LSQAlphaAccumulateAVX2(samples *[16]uint8, aa uint32, out *[5]int32)

// DownscaleNRGBARow2xAVX2 downsamples one NRGBA row by 2x using an exact rounded 2x2 box filter.
// n is the even number of output pixels to write; odd tails and clamp edges are handled by Go.
//
//go:noescape
func DownscaleNRGBARow2xAVX2(dst *byte, row0 *byte, row1 *byte, n int)
