// Code generated by command: go run gen.go -out ../kernels_amd64.s -stubs ../kernels_stubs_amd64.go -pkg simd. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func FindMinMaxSSE2(block *[64]byte) uint64
// Requires: SSE2
TEXT ·FindMinMaxSSE2(SB), NOSPLIT, $0-16
	MOVQ      block+0(FP), AX
	MOVOU     (AX), X0
	MOVOU     16(AX), X1
	MOVOU     32(AX), X2
	MOVOU     48(AX), X3
	MOVOU     X0, X4
	PMINUB    X1, X4
	PMAXUB    X1, X0
	PMINUB    X2, X4
	PMAXUB    X2, X0
	PMINUB    X3, X4
	PMAXUB    X3, X0
	PSHUFD    $0x4e, X4, X1
	PMINUB    X1, X4
	PSHUFD    $0xe5, X4, X1
	PMINUB    X1, X4
	PSHUFD    $0x4e, X0, X1
	PMAXUB    X1, X0
	PSHUFD    $0xe5, X0, X1
	PMAXUB    X1, X0
	PUNPCKLLQ X0, X4
	MOVQ      X4, AX
	MOVQ      AX, ret+8(FP)
	RET

DATA decodeIdxShiftsLo<>+0(SB)/4, $0x00000000
DATA decodeIdxShiftsLo<>+4(SB)/4, $0x00000002
DATA decodeIdxShiftsLo<>+8(SB)/4, $0x00000004
DATA decodeIdxShiftsLo<>+12(SB)/4, $0x00000006
DATA decodeIdxShiftsLo<>+16(SB)/4, $0x00000008
DATA decodeIdxShiftsLo<>+20(SB)/4, $0x0000000a
DATA decodeIdxShiftsLo<>+24(SB)/4, $0x0000000c
DATA decodeIdxShiftsLo<>+28(SB)/4, $0x0000000e
GLOBL decodeIdxShiftsLo<>(SB), RODATA|NOPTR, $32

DATA decodeIdxShiftsHi<>+0(SB)/4, $0x00000010
DATA decodeIdxShiftsHi<>+4(SB)/4, $0x00000012
DATA decodeIdxShiftsHi<>+8(SB)/4, $0x00000014
DATA decodeIdxShiftsHi<>+12(SB)/4, $0x00000016
DATA decodeIdxShiftsHi<>+16(SB)/4, $0x00000018
DATA decodeIdxShiftsHi<>+20(SB)/4, $0x0000001a
DATA decodeIdxShiftsHi<>+24(SB)/4, $0x0000001c
DATA decodeIdxShiftsHi<>+28(SB)/4, $0x0000001e
GLOBL decodeIdxShiftsHi<>(SB), RODATA|NOPTR, $32

DATA decodeAlphaPalConsts<>+0(SB)/2, $0x0007
DATA decodeAlphaPalConsts<>+2(SB)/2, $0x0000
DATA decodeAlphaPalConsts<>+4(SB)/2, $0x0006
DATA decodeAlphaPalConsts<>+6(SB)/2, $0x0005
DATA decodeAlphaPalConsts<>+8(SB)/2, $0x0004
DATA decodeAlphaPalConsts<>+10(SB)/2, $0x0003
DATA decodeAlphaPalConsts<>+12(SB)/2, $0x0002
DATA decodeAlphaPalConsts<>+14(SB)/2, $0x0001
DATA decodeAlphaPalConsts<>+16(SB)/2, $0x0000
DATA decodeAlphaPalConsts<>+18(SB)/2, $0x0007
DATA decodeAlphaPalConsts<>+20(SB)/2, $0x0001
DATA decodeAlphaPalConsts<>+22(SB)/2, $0x0002
DATA decodeAlphaPalConsts<>+24(SB)/2, $0x0003
DATA decodeAlphaPalConsts<>+26(SB)/2, $0x0004
DATA decodeAlphaPalConsts<>+28(SB)/2, $0x0005
DATA decodeAlphaPalConsts<>+30(SB)/2, $0x0006
DATA decodeAlphaPalConsts<>+32(SB)/2, $0x0003
DATA decodeAlphaPalConsts<>+34(SB)/2, $0x0003
DATA decodeAlphaPalConsts<>+36(SB)/2, $0x0003
DATA decodeAlphaPalConsts<>+38(SB)/2, $0x0003
DATA decodeAlphaPalConsts<>+40(SB)/2, $0x0003
DATA decodeAlphaPalConsts<>+42(SB)/2, $0x0003
DATA decodeAlphaPalConsts<>+44(SB)/2, $0x0003
DATA decodeAlphaPalConsts<>+46(SB)/2, $0x0003
DATA decodeAlphaPalConsts<>+48(SB)/2, $0x2493
DATA decodeAlphaPalConsts<>+50(SB)/2, $0x2493
DATA decodeAlphaPalConsts<>+52(SB)/2, $0x2493
DATA decodeAlphaPalConsts<>+54(SB)/2, $0x2493
DATA decodeAlphaPalConsts<>+56(SB)/2, $0x2493
DATA decodeAlphaPalConsts<>+58(SB)/2, $0x2493
DATA decodeAlphaPalConsts<>+60(SB)/2, $0x2493
DATA decodeAlphaPalConsts<>+62(SB)/2, $0x2493
DATA decodeAlphaPalConsts<>+64(SB)/2, $0x0005
DATA decodeAlphaPalConsts<>+66(SB)/2, $0x0000
DATA decodeAlphaPalConsts<>+68(SB)/2, $0x0004
DATA decodeAlphaPalConsts<>+70(SB)/2, $0x0003
DATA decodeAlphaPalConsts<>+72(SB)/2, $0x0002
DATA decodeAlphaPalConsts<>+74(SB)/2, $0x0001
DATA decodeAlphaPalConsts<>+76(SB)/2, $0x0000
DATA decodeAlphaPalConsts<>+78(SB)/2, $0x0000
DATA decodeAlphaPalConsts<>+80(SB)/2, $0x0000
DATA decodeAlphaPalConsts<>+82(SB)/2, $0x0005
DATA decodeAlphaPalConsts<>+84(SB)/2, $0x0001
DATA decodeAlphaPalConsts<>+86(SB)/2, $0x0002
DATA decodeAlphaPalConsts<>+88(SB)/2, $0x0003
DATA decodeAlphaPalConsts<>+90(SB)/2, $0x0004
DATA decodeAlphaPalConsts<>+92(SB)/2, $0x0000
DATA decodeAlphaPalConsts<>+94(SB)/2, $0x0000
DATA decodeAlphaPalConsts<>+96(SB)/2, $0x0002
DATA decodeAlphaPalConsts<>+98(SB)/2, $0x0002
DATA decodeAlphaPalConsts<>+100(SB)/2, $0x0002
DATA decodeAlphaPalConsts<>+102(SB)/2, $0x0002
DATA decodeAlphaPalConsts<>+104(SB)/2, $0x0002
DATA decodeAlphaPalConsts<>+106(SB)/2, $0x0002
DATA decodeAlphaPalConsts<>+108(SB)/2, $0x0000
DATA decodeAlphaPalConsts<>+110(SB)/2, $0x04fd
DATA decodeAlphaPalConsts<>+112(SB)/2, $0x3334
DATA decodeAlphaPalConsts<>+114(SB)/2, $0x3334
DATA decodeAlphaPalConsts<>+116(SB)/2, $0x3334
DATA decodeAlphaPalConsts<>+118(SB)/2, $0x3334
DATA decodeAlphaPalConsts<>+120(SB)/2, $0x3334
DATA decodeAlphaPalConsts<>+122(SB)/2, $0x3334
DATA decodeAlphaPalConsts<>+124(SB)/2, $0x3334
DATA decodeAlphaPalConsts<>+126(SB)/2, $0x3334
GLOBL decodeAlphaPalConsts<>(SB), RODATA|NOPTR, $128

DATA decodeGrayMul<>+0(SB)/4, $0x00010101
GLOBL decodeGrayMul<>(SB), RODATA|NOPTR, $4

// func DecodeDXT1RowAVX2(dst *byte, src *byte, n int, stride int)
// Requires: AVX, AVX2
TEXT ·DecodeDXT1RowAVX2(SB), NOSPLIT, $0-32
	MOVQ     dst+0(FP), AX
	MOVQ     src+8(FP), CX
	MOVQ     n+16(FP), DX
	MOVQ     stride+24(FP), BX
	VMOVDQU  decodeIdxShiftsLo<>+0(SB), Y0
	VMOVDQU  decodeIdxShiftsHi<>+0(SB), Y1
	VPCMPEQD Y2, Y2, Y2
	VPSRLD   $0x1e, Y2, Y2

loop:
	MOVWLZX (CX), SI
	MOVWLZX 2(CX), DI
	MOVL    SI, R8
	SHRL    $0x0b, R8
	IMUL3Q  $0x0000020f, R8, R8
	ADDL    $0x17, R8
	SHRL    $0x06, R8
	MOVL    SI, R9
	SHRL    $0x05, R9
	ANDL    $0x3f, R9
	IMUL3Q  $0x00000103, R9, R9
	ADDL    $0x21, R9
	SHRL    $0x06, R9
	MOVL    SI, R10
	ANDL    $0x1f, R10
	IMUL3Q  $0x0000020f, R10, R10
	ADDL    $0x17, R10
	SHRL    $0x06, R10
	MOVL    R9, R11
	SHLL    $0x08, R11
	ORL     R8, R11
	MOVL    R10, R12
	SHLL    $0x10, R12
	ORL     R12, R11
	ORL     $0xff000000, R11
	VMOVD   R11, X3
	MOVL    DI, R11
	SHRL    $0x0b, R11
	IMUL3Q  $0x0000020f, R11, R11
	ADDL    $0x17, R11
	SHRL    $0x06, R11
	MOVL    DI, R12
	SHRL    $0x05, R12
	ANDL    $0x3f, R12
	IMUL3Q  $0x00000103, R12, R12
	ADDL    $0x21, R12
	SHRL    $0x06, R12
	MOVL    DI, R13
	ANDL    $0x1f, R13
	IMUL3Q  $0x0000020f, R13, R13
	ADDL    $0x17, R13
	SHRL    $0x06, R13
	MOVL    R12, R14
	SHLL    $0x08, R14
	ORL     R11, R14
	MOVL    R13, R15
	SHLL    $0x10, R15
	ORL     R15, R14
	ORL     $0xff000000, R14
	VPINSRD $0x01, R14, X3, X3
	CMPL    SI, DI
	JHI     mode4
	LEAQ    (R8)(R11*1), SI
	SHRL    $0x01, SI
	LEAQ    (R9)(R12*1), DI
	SHRL    $0x01, DI
	LEAQ    (R10)(R13*1), R8
	SHRL    $0x01, R8
	SHLL    $0x08, DI
	ORL     SI, DI
	MOVL    R8, SI
	SHLL    $0x10, SI
	ORL     SI, DI
	ORL     $0xff000000, DI
	VPINSRD $0x02, DI, X3, X3
	JMP     merge

mode4:
	LEAQ    1(R11)(R8*2), SI
	IMUL3Q  $0x000002ab, SI, SI
	SHRL    $0x0b, SI
	LEAQ    1(R8)(R11*2), DI
	IMUL3Q  $0x000002ab, DI, DI
	SHRL    $0x0b, DI
	LEAQ    1(R12)(R9*2), R8
	IMUL3Q  $0x000002ab, R8, R8
	SHRL    $0x0b, R8
	LEAQ    1(R9)(R12*2), R9
	IMUL3Q  $0x000002ab, R9, R9
	SHRL    $0x0b, R9
	LEAQ    1(R13)(R10*2), R11
	IMUL3Q  $0x000002ab, R11, R11
	SHRL    $0x0b, R11
	LEAQ    1(R10)(R13*2), R10
	IMUL3Q  $0x000002ab, R10, R10
	SHRL    $0x0b, R10
	SHLL    $0x08, R8
	ORL     SI, R8
	MOVL    R11, SI
	SHLL    $0x10, SI
	ORL     SI, R8
	ORL     $0xff000000, R8
	VPINSRD $0x02, R8, X3, X3
	MOVL    R9, SI
	SHLL    $0x08, SI
	ORL     DI, SI
	MOVL    R10, DI
	SHLL    $0x10, DI
	ORL     DI, SI
	ORL     $0xff000000, SI
	VPINSRD $0x03, SI, X3, X3

merge:
	VPBROADCASTD 4(CX), Y4
	VPSRLVD      Y0, Y4, Y5
	VPAND        Y2, Y5, Y5
	VPSRLVD      Y1, Y4, Y4
	VPAND        Y2, Y4, Y4
	VPERMD       Y3, Y5, Y5
	VPERMD       Y3, Y4, Y4
	VMOVDQU      X5, (AX)
	VEXTRACTI128 $0x01, Y5, (AX)(BX*1)
	LEAQ         (AX)(BX*2), SI
	VMOVDQU      X4, (SI)
	VEXTRACTI128 $0x01, Y4, (SI)(BX*1)
	ADDQ         $0x08, CX
	ADDQ         $0x10, AX
	DECQ         DX
	JNZ          loop
	VZEROUPPER
	RET

// func DecodeDXT3RowAVX2(dst *byte, src *byte, n int, stride int)
// Requires: AVX, AVX2, BMI2
TEXT ·DecodeDXT3RowAVX2(SB), NOSPLIT, $0-32
	MOVQ     dst+0(FP), AX
	MOVQ     src+8(FP), CX
	MOVQ     n+16(FP), DX
	MOVQ     stride+24(FP), BX
	VMOVDQU  decodeIdxShiftsLo<>+0(SB), Y0
	VMOVDQU  decodeIdxShiftsHi<>+0(SB), Y1
	VPCMPEQD Y2, Y2, Y2
	VPSRLD   $0x1e, Y2, Y2
	VPCMPEQD Y3, Y3, Y3
	VPSRLD   $0x08, Y3, Y3

loop:
	MOVQ    $0x0f0f0f0f0f0f0f0f, SI
	MOVL    (CX), DI
	PDEPQ   SI, DI, DI
	MOVL    4(CX), R8
	PDEPQ   SI, R8, SI
	VMOVQ   DI, X4
	VPINSRQ $0x01, SI, X4, X4
	MOVWLZX 8(CX), SI
	MOVWLZX 10(CX), DI
	MOVL    SI, R8
	SHRL    $0x0b, R8
	IMUL3Q  $0x0000020f, R8, R8
	ADDL    $0x17, R8
	SHRL    $0x06, R8
	MOVL    SI, R9
	SHRL    $0x05, R9
	ANDL    $0x3f, R9
	IMUL3Q  $0x00000103, R9, R9
	ADDL    $0x21, R9
	SHRL    $0x06, R9
	MOVL    SI, R10
	ANDL    $0x1f, R10
	IMUL3Q  $0x0000020f, R10, R10
	ADDL    $0x17, R10
	SHRL    $0x06, R10
	MOVL    R9, R11
	SHLL    $0x08, R11
	ORL     R8, R11
	MOVL    R10, R12
	SHLL    $0x10, R12
	ORL     R12, R11
	ORL     $0xff000000, R11
	VMOVD   R11, X5
	MOVL    DI, R11
	SHRL    $0x0b, R11
	IMUL3Q  $0x0000020f, R11, R11
	ADDL    $0x17, R11
	SHRL    $0x06, R11
	MOVL    DI, R12
	SHRL    $0x05, R12
	ANDL    $0x3f, R12
	IMUL3Q  $0x00000103, R12, R12
	ADDL    $0x21, R12
	SHRL    $0x06, R12
	MOVL    DI, R13
	ANDL    $0x1f, R13
	IMUL3Q  $0x0000020f, R13, R13
	ADDL    $0x17, R13
	SHRL    $0x06, R13
	MOVL    R12, R14
	SHLL    $0x08, R14
	ORL     R11, R14
	MOVL    R13, R15
	SHLL    $0x10, R15
	ORL     R15, R14
	ORL     $0xff000000, R14
	VPINSRD $0x01, R14, X5, X5
	CMPL    SI, DI
	JHI     mode4
	LEAQ    (R8)(R11*1), SI
	SHRL    $0x01, SI
	LEAQ    (R9)(R12*1), DI
	SHRL    $0x01, DI
	LEAQ    (R10)(R13*1), R8
	SHRL    $0x01, R8
	SHLL    $0x08, DI
	ORL     SI, DI
	MOVL    R8, SI
	SHLL    $0x10, SI
	ORL     SI, DI
	ORL     $0xff000000, DI
	VPINSRD $0x02, DI, X5, X5
	JMP     merge

mode4:
	LEAQ    1(R11)(R8*2), SI
	IMUL3Q  $0x000002ab, SI, SI
	SHRL    $0x0b, SI
	LEAQ    1(R8)(R11*2), DI
	IMUL3Q  $0x000002ab, DI, DI
	SHRL    $0x0b, DI
	LEAQ    1(R12)(R9*2), R8
	IMUL3Q  $0x000002ab, R8, R8
	SHRL    $0x0b, R8
	LEAQ    1(R9)(R12*2), R9
	IMUL3Q  $0x000002ab, R9, R9
	SHRL    $0x0b, R9
	LEAQ    1(R13)(R10*2), R11
	IMUL3Q  $0x000002ab, R11, R11
	SHRL    $0x0b, R11
	LEAQ    1(R10)(R13*2), R10
	IMUL3Q  $0x000002ab, R10, R10
	SHRL    $0x0b, R10
	SHLL    $0x08, R8
	ORL     SI, R8
	MOVL    R11, SI
	SHLL    $0x10, SI
	ORL     SI, R8
	ORL     $0xff000000, R8
	VPINSRD $0x02, R8, X5, X5
	MOVL    R9, SI
	SHLL    $0x08, SI
	ORL     DI, SI
	MOVL    R10, DI
	SHLL    $0x10, DI
	ORL     DI, SI
	ORL     $0xff000000, SI
	VPINSRD $0x03, SI, X5, X5

merge:
	VPBROADCASTD 12(CX), Y6
	VPSRLVD      Y0, Y6, Y7
	VPAND        Y2, Y7, Y7
	VPSRLVD      Y1, Y6, Y6
	VPAND        Y2, Y6, Y6
	VPERMD       Y5, Y7, Y7
	VPERMD       Y5, Y6, Y6
	VPAND        Y3, Y7, Y7
	VPAND        Y3, Y6, Y6
	VPMOVZXBD    X4, Y8
	VPSLLD       $0x04, Y8, Y9
	VPADDD       Y9, Y8, Y8
	VPSLLD       $0x18, Y8, Y8
	VPOR         Y8, Y7, Y7
	VPSRLDQ      $0x08, X4, X4
	VPMOVZXBD    X4, Y4
	VPSLLD       $0x04, Y4, Y8
	VPADDD       Y8, Y4, Y4
	VPSLLD       $0x18, Y4, Y4
	VPOR         Y4, Y6, Y6
	VMOVDQU      X7, (AX)
	VEXTRACTI128 $0x01, Y7, (AX)(BX*1)
	LEAQ         (AX)(BX*2), SI
	VMOVDQU      X6, (SI)
	VEXTRACTI128 $0x01, Y6, (SI)(BX*1)
	ADDQ         $0x10, CX
	ADDQ         $0x10, AX
	DECQ         DX
	JNZ          loop
	VZEROUPPER
	RET

// func DecodeDXT5RowAVX2(dst *byte, src *byte, n int, stride int)
// Requires: AVX, AVX2, BMI2, CMOV
TEXT ·DecodeDXT5RowAVX2(SB), NOSPLIT, $0-32
	MOVQ     dst+0(FP), AX
	MOVQ     src+8(FP), CX
	MOVQ     n+16(FP), DX
	MOVQ     stride+24(FP), BX
	VMOVDQU  decodeIdxShiftsLo<>+0(SB), Y0
	VMOVDQU  decodeIdxShiftsHi<>+0(SB), Y1
	VPCMPEQD Y2, Y2, Y2
	VPSRLD   $0x1e, Y2, Y2
	VPCMPEQD Y3, Y3, Y3
	VPSRLD   $0x08, Y3, Y3

loop:
	MOVBLZX      (CX), SI
	MOVBLZX      1(CX), DI
	LEAQ         decodeAlphaPalConsts<>+64(SB), R8
	LEAQ         decodeAlphaPalConsts<>+0(SB), R9
	CMPL         SI, DI
	CMOVQHI      R9, R8
	VMOVD        SI, X4
	VPBROADCASTW X4, X4
	VMOVD        DI, X5
	VPBROADCASTW X5, X5
	VPMULLW      (R8), X4, X4
	VPMULLW      16(R8), X5, X5
	VPADDW       X5, X4, X4
	VPADDW       32(R8), X4, X4
	VPMULHUW     48(R8), X4, X4
	VPACKUSWB    X4, X4, X4
	MOVL         2(CX), SI
	MOVWLZX      6(CX), DI
	SHLQ         $0x20, DI
	ORQ          DI, SI
	MOVQ         $0x0707070707070707, DI
	PDEPQ        DI, SI, R8
	SHRQ         $0x18, SI
	PDEPQ        DI, SI, SI
	VMOVQ        R8, X5
	VPINSRQ      $0x01, SI, X5, X5
	VPSHUFB      X5, X4, X4
	MOVWLZX      8(CX), SI
	MOVWLZX      10(CX), DI
	MOVL         SI, R8
	SHRL         $0x0b, R8
	IMUL3Q       $0x0000020f, R8, R8
	ADDL         $0x17, R8
	SHRL         $0x06, R8
	MOVL         SI, R9
	SHRL         $0x05, R9
	ANDL         $0x3f, R9
	IMUL3Q       $0x00000103, R9, R9
	ADDL         $0x21, R9
	SHRL         $0x06, R9
	MOVL         SI, R10
	ANDL         $0x1f, R10
	IMUL3Q       $0x0000020f, R10, R10
	ADDL         $0x17, R10
	SHRL         $0x06, R10
	MOVL         R9, R11
	SHLL         $0x08, R11
	ORL          R8, R11
	MOVL         R10, R12
	SHLL         $0x10, R12
	ORL          R12, R11
	ORL          $0xff000000, R11
	VMOVD        R11, X5
	MOVL         DI, R11
	SHRL         $0x0b, R11
	IMUL3Q       $0x0000020f, R11, R11
	ADDL         $0x17, R11
	SHRL         $0x06, R11
	MOVL         DI, R12
	SHRL         $0x05, R12
	ANDL         $0x3f, R12
	IMUL3Q       $0x00000103, R12, R12
	ADDL         $0x21, R12
	SHRL         $0x06, R12
	MOVL         DI, R13
	ANDL         $0x1f, R13
	IMUL3Q       $0x0000020f, R13, R13
	ADDL         $0x17, R13
	SHRL         $0x06, R13
	MOVL         R12, R14
	SHLL         $0x08, R14
	ORL          R11, R14
	MOVL         R13, R15
	SHLL         $0x10, R15
	ORL          R15, R14
	ORL          $0xff000000, R14
	VPINSRD      $0x01, R14, X5, X5
	CMPL         SI, DI
	JHI          mode4
	LEAQ         (R8)(R11*1), SI
	SHRL         $0x01, SI
	LEAQ         (R9)(R12*1), DI
	SHRL         $0x01, DI
	LEAQ         (R10)(R13*1), R8
	SHRL         $0x01, R8
	SHLL         $0x08, DI
	ORL          SI, DI
	MOVL         R8, SI
	SHLL         $0x10, SI
	ORL          SI, DI
	ORL          $0xff000000, DI
	VPINSRD      $0x02, DI, X5, X5
	JMP          merge

mode4:
	LEAQ    1(R11)(R8*2), SI
	IMUL3Q  $0x000002ab, SI, SI
	SHRL    $0x0b, SI
	LEAQ    1(R8)(R11*2), DI
	IMUL3Q  $0x000002ab, DI, DI
	SHRL    $0x0b, DI
	LEAQ    1(R12)(R9*2), R8
	IMUL3Q  $0x000002ab, R8, R8
	SHRL    $0x0b, R8
	LEAQ    1(R9)(R12*2), R9
	IMUL3Q  $0x000002ab, R9, R9
	SHRL    $0x0b, R9
	LEAQ    1(R13)(R10*2), R11
	IMUL3Q  $0x000002ab, R11, R11
	SHRL    $0x0b, R11
	LEAQ    1(R10)(R13*2), R10
	IMUL3Q  $0x000002ab, R10, R10
	SHRL    $0x0b, R10
	SHLL    $0x08, R8
	ORL     SI, R8
	MOVL    R11, SI
	SHLL    $0x10, SI
	ORL     SI, R8
	ORL     $0xff000000, R8
	VPINSRD $0x02, R8, X5, X5
	MOVL    R9, SI
	SHLL    $0x08, SI
	ORL     DI, SI
	MOVL    R10, DI
	SHLL    $0x10, DI
	ORL     DI, SI
	ORL     $0xff000000, SI
	VPINSRD $0x03, SI, X5, X5

merge:
	VPBROADCASTD 12(CX), Y6
	VPSRLVD      Y0, Y6, Y7
	VPAND        Y2, Y7, Y7
	VPSRLVD      Y1, Y6, Y6
	VPAND        Y2, Y6, Y6
	VPERMD       Y5, Y7, Y7
	VPERMD       Y5, Y6, Y6
	VPAND        Y3, Y7, Y7
	VPAND        Y3, Y6, Y6
	VPMOVZXBD    X4, Y8
	VPSLLD       $0x18, Y8, Y8
	VPOR         Y8, Y7, Y7
	VPSRLDQ      $0x08, X4, X4
	VPMOVZXBD    X4, Y8
	VPSLLD       $0x18, Y8, Y8
	VPOR         Y8, Y6, Y6
	VMOVDQU      X7, (AX)
	VEXTRACTI128 $0x01, Y7, (AX)(BX*1)
	LEAQ         (AX)(BX*2), SI
	VMOVDQU      X6, (SI)
	VEXTRACTI128 $0x01, Y6, (SI)(BX*1)
	ADDQ         $0x10, CX
	ADDQ         $0x10, AX
	DECQ         DX
	JNZ          loop
	VZEROUPPER
	RET

// func DecodeBC4RowAVX2(dst *byte, src *byte, n int, stride int)
// Requires: AVX, AVX2, BMI2, CMOV
TEXT ·DecodeBC4RowAVX2(SB), NOSPLIT, $0-32
	MOVQ         dst+0(FP), AX
	MOVQ         src+8(FP), CX
	MOVQ         n+16(FP), DX
	MOVQ         stride+24(FP), BX
	VPBROADCASTD decodeGrayMul<>+0(SB), Y0
	VPCMPEQD     Y1, Y1, Y1
	VPSLLD       $0x18, Y1, Y1

loop:
	MOVBLZX      (CX), SI
	MOVBLZX      1(CX), DI
	LEAQ         decodeAlphaPalConsts<>+64(SB), R8
	LEAQ         decodeAlphaPalConsts<>+0(SB), R9
	CMPL         SI, DI
	CMOVQHI      R9, R8
	VMOVD        SI, X2
	VPBROADCASTW X2, X2
	VMOVD        DI, X3
	VPBROADCASTW X3, X3
	VPMULLW      (R8), X2, X2
	VPMULLW      16(R8), X3, X3
	VPADDW       X3, X2, X2
	VPADDW       32(R8), X2, X2
	VPMULHUW     48(R8), X2, X2
	VPACKUSWB    X2, X2, X2
	MOVL         2(CX), SI
	MOVWLZX      6(CX), DI
	SHLQ         $0x20, DI
	ORQ          DI, SI
	MOVQ         $0x0707070707070707, DI
	PDEPQ        DI, SI, R8
	SHRQ         $0x18, SI
	PDEPQ        DI, SI, SI
	VMOVQ        R8, X3
	VPINSRQ      $0x01, SI, X3, X3
	VPSHUFB      X3, X2, X2
	VPMOVZXBD    X2, Y3
	VPMULLD      Y0, Y3, Y3
	VPOR         Y1, Y3, Y3
	VPSRLDQ      $0x08, X2, X2
	VPMOVZXBD    X2, Y2
	VPMULLD      Y0, Y2, Y2
	VPOR         Y1, Y2, Y2
	VMOVDQU      X3, (AX)
	VEXTRACTI128 $0x01, Y3, (AX)(BX*1)
	LEAQ         (AX)(BX*2), SI
	VMOVDQU      X2, (SI)
	VEXTRACTI128 $0x01, Y2, (SI)(BX*1)
	ADDQ         $0x08, CX
	ADDQ         $0x10, AX
	DECQ         DX
	JNZ          loop
	VZEROUPPER
	RET

// func DecodeBC5RowAVX2(dst *byte, src *byte, n int, stride int)
// Requires: AVX, AVX2, BMI2, CMOV
TEXT ·DecodeBC5RowAVX2(SB), NOSPLIT, $0-32
	MOVQ     dst+0(FP), AX
	MOVQ     src+8(FP), CX
	MOVQ     n+16(FP), DX
	MOVQ     stride+24(FP), BX
	VPCMPEQD Y0, Y0, Y0
	VPSLLD   $0x18, Y0, Y0

loop:
	MOVBLZX      (CX), SI
	MOVBLZX      1(CX), DI
	LEAQ         decodeAlphaPalConsts<>+64(SB), R8
	LEAQ         decodeAlphaPalConsts<>+0(SB), R9
	CMPL         SI, DI
	CMOVQHI      R9, R8
	VMOVD        SI, X1
	VPBROADCASTW X1, X1
	VMOVD        DI, X2
	VPBROADCASTW X2, X2
	VPMULLW      (R8), X1, X1
	VPMULLW      16(R8), X2, X2
	VPADDW       X2, X1, X1
	VPADDW       32(R8), X1, X1
	VPMULHUW     48(R8), X1, X1
	VPACKUSWB    X1, X1, X1
	MOVL         2(CX), SI
	MOVWLZX      6(CX), DI
	SHLQ         $0x20, DI
	ORQ          DI, SI
	MOVQ         $0x0707070707070707, DI
	PDEPQ        DI, SI, R8
	SHRQ         $0x18, SI
	PDEPQ        DI, SI, SI
	VMOVQ        R8, X2
	VPINSRQ      $0x01, SI, X2, X2
	VPSHUFB      X2, X1, X1
	MOVBLZX      8(CX), SI
	MOVBLZX      9(CX), DI
	LEAQ         decodeAlphaPalConsts<>+64(SB), R8
	LEAQ         decodeAlphaPalConsts<>+0(SB), R9
	CMPL         SI, DI
	CMOVQHI      R9, R8
	VMOVD        SI, X2
	VPBROADCASTW X2, X2
	VMOVD        DI, X3
	VPBROADCASTW X3, X3
	VPMULLW      (R8), X2, X2
	VPMULLW      16(R8), X3, X3
	VPADDW       X3, X2, X2
	VPADDW       32(R8), X2, X2
	VPMULHUW     48(R8), X2, X2
	VPACKUSWB    X2, X2, X2
	MOVL         10(CX), SI
	MOVWLZX      14(CX), DI
	SHLQ         $0x20, DI
	ORQ          DI, SI
	MOVQ         $0x0707070707070707, DI
	PDEPQ        DI, SI, R8
	SHRQ         $0x18, SI
	PDEPQ        DI, SI, SI
	VMOVQ        R8, X3
	VPINSRQ      $0x01, SI, X3, X3
	VPSHUFB      X3, X2, X2
	VPUNPCKLBW   X2, X1, X3
	VPMOVZXWD    X3, Y3
	VPOR         Y0, Y3, Y3
	VPUNPCKHBW   X2, X1, X1
	VPMOVZXWD    X1, Y1
	VPOR         Y0, Y1, Y1
	VMOVDQU      X3, (AX)
	VEXTRACTI128 $0x01, Y3, (AX)(BX*1)
	LEAQ         (AX)(BX*2), SI
	VMOVDQU      X1, (SI)
	VEXTRACTI128 $0x01, Y1, (SI)(BX*1)
	ADDQ         $0x10, CX
	ADDQ         $0x10, AX
	DECQ         DX
	JNZ          loop
	VZEROUPPER
	RET

// func PackDXT1IndicesAVX2(block *[64]byte, params *[20]int32) uint32
// Requires: AVX, AVX2
TEXT ·PackDXT1IndicesAVX2(SB), NOSPLIT, $0-20
	MOVQ         block+0(FP), AX
	MOVQ         params+8(FP), CX
	VPCMPEQD     Y0, Y0, Y0
	VPSRLD       $0x18, Y0, Y1
	VPSRLD       $0x1f, Y0, Y2
	VPSRLD       $0x1e, Y0, Y0
	VPBROADCASTD 48(CX), Y3
	VPBROADCASTD 52(CX), Y4
	VPBROADCASTD 56(CX), Y5
	VMOVDQU      (AX), Y6
	VPAND        Y1, Y6, Y7
	VPSRLD       $0x08, Y6, Y8
	VPAND        Y1, Y8, Y8
	VPSRLD       $0x10, Y6, Y9
	VPAND        Y1, Y9, Y9
	VPSRLD       $0x18, Y6, Y6
	VPBROADCASTD (CX), Y11
	VPSUBD       Y11, Y7, Y10
	VPMULLD      Y10, Y10, Y10
	VPMULLD      Y3, Y10, Y10
	VPBROADCASTD 16(CX), Y11
	VPSUBD       Y11, Y8, Y11
	VPMULLD      Y11, Y11, Y11
	VPMULLD      Y4, Y11, Y11
	VPADDD       Y11, Y10, Y10
	VPBROADCASTD 32(CX), Y11
	VPSUBD       Y11, Y9, Y11
	VPMULLD      Y11, Y11, Y11
	VPMULLD      Y5, Y11, Y11
	VPADDD       Y11, Y10, Y10
	VPXOR        Y11, Y11, Y11
	VPBROADCASTD 4(CX), Y13
	VPSUBD       Y13, Y7, Y12
	VPMULLD      Y12, Y12, Y12
	VPMULLD      Y3, Y12, Y12
	VPBROADCASTD 20(CX), Y13
	VPSUBD       Y13, Y8, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y4, Y13, Y13
	VPADDD       Y13, Y12, Y12
	VPBROADCASTD 36(CX), Y13
	VPSUBD       Y13, Y9, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y5, Y13, Y13
	VPADDD       Y13, Y12, Y12
	VPCMPGTD     Y12, Y10, Y13
	VPBLENDVB    Y13, Y12, Y10, Y10
	VPBLENDVB    Y13, Y2, Y11, Y11
	VPSLLD       $0x01, Y2, Y12
	VPBROADCASTD 8(CX), Y14
	VPSUBD       Y14, Y7, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y3, Y13, Y13
	VPBROADCASTD 24(CX), Y14
	VPSUBD       Y14, Y8, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y4, Y14, Y14
	VPADDD       Y14, Y13, Y13
	VPBROADCASTD 40(CX), Y14
	VPSUBD       Y14, Y9, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y5, Y14, Y14
	VPADDD       Y14, Y13, Y13
	VPCMPGTD     Y13, Y10, Y14
	VPBLENDVB    Y14, Y13, Y10, Y10
	VPBLENDVB    Y14, Y12, Y11, Y11
	VPBROADCASTD 12(CX), Y12
	VPSUBD       Y12, Y7, Y7
	VPMULLD      Y7, Y7, Y7
	VPMULLD      Y3, Y7, Y7
	VPBROADCASTD 28(CX), Y12
	VPSUBD       Y12, Y8, Y12
	VPMULLD      Y12, Y12, Y12
	VPMULLD      Y4, Y12, Y12
	VPADDD       Y12, Y7, Y7
	VPBROADCASTD 44(CX), Y12
	VPSUBD       Y12, Y9, Y12
	VPMULLD      Y12, Y12, Y12
	VPMULLD      Y5, Y12, Y12
	VPADDD       Y12, Y7, Y7
	VPBROADCASTD 64(CX), Y8
	VPADDD       Y8, Y7, Y7
	VPCMPGTD     Y7, Y10, Y8
	VPBLENDVB    Y8, Y7, Y10, Y10
	VPBLENDVB    Y8, Y0, Y11, Y11
	VPBROADCASTD 60(CX), Y7
	VPCMPGTD     Y6, Y7, Y7
	VPBLENDVB    Y7, Y0, Y11, Y11
	VPSLLVD      decodeIdxShiftsLo<>+0(SB), Y11, Y11
	VMOVDQU      32(AX), Y6
	VPAND        Y1, Y6, Y7
	VPSRLD       $0x08, Y6, Y8
	VPAND        Y1, Y8, Y8
	VPSRLD       $0x10, Y6, Y9
	VPAND        Y1, Y9, Y9
	VPSRLD       $0x18, Y6, Y1
	VPBROADCASTD (CX), Y10
	VPSUBD       Y10, Y7, Y6
	VPMULLD      Y6, Y6, Y6
	VPMULLD      Y3, Y6, Y6
	VPBROADCASTD 16(CX), Y10
	VPSUBD       Y10, Y8, Y10
	VPMULLD      Y10, Y10, Y10
	VPMULLD      Y4, Y10, Y10
	VPADDD       Y10, Y6, Y6
	VPBROADCASTD 32(CX), Y10
	VPSUBD       Y10, Y9, Y10
	VPMULLD      Y10, Y10, Y10
	VPMULLD      Y5, Y10, Y10
	VPADDD       Y10, Y6, Y6
	VPXOR        Y10, Y10, Y10
	VPBROADCASTD 4(CX), Y13
	VPSUBD       Y13, Y7, Y12
	VPMULLD      Y12, Y12, Y12
	VPMULLD      Y3, Y12, Y12
	VPBROADCASTD 20(CX), Y13
	VPSUBD       Y13, Y8, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y4, Y13, Y13
	VPADDD       Y13, Y12, Y12
	VPBROADCASTD 36(CX), Y13
	VPSUBD       Y13, Y9, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y5, Y13, Y13
	VPADDD       Y13, Y12, Y12
	VPCMPGTD     Y12, Y6, Y13
	VPBLENDVB    Y13, Y12, Y6, Y6
	VPBLENDVB    Y13, Y2, Y10, Y10
	VPSLLD       $0x01, Y2, Y2
	VPBROADCASTD 8(CX), Y13
	VPSUBD       Y13, Y7, Y12
	VPMULLD      Y12, Y12, Y12
	VPMULLD      Y3, Y12, Y12
	VPBROADCASTD 24(CX), Y13
	VPSUBD       Y13, Y8, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y4, Y13, Y13
	VPADDD       Y13, Y12, Y12
	VPBROADCASTD 40(CX), Y13
	VPSUBD       Y13, Y9, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y5, Y13, Y13
	VPADDD       Y13, Y12, Y12
	VPCMPGTD     Y12, Y6, Y13
	VPBLENDVB    Y13, Y12, Y6, Y6
	VPBLENDVB    Y13, Y2, Y10, Y10
	VPBROADCASTD 12(CX), Y2
	VPSUBD       Y2, Y7, Y7
	VPMULLD      Y7, Y7, Y7
	VPMULLD      Y3, Y7, Y7
	VPBROADCASTD 28(CX), Y2
	VPSUBD       Y2, Y8, Y2
	VPMULLD      Y2, Y2, Y2
	VPMULLD      Y4, Y2, Y2
	VPADDD       Y2, Y7, Y7
	VPBROADCASTD 44(CX), Y2
	VPSUBD       Y2, Y9, Y2
	VPMULLD      Y2, Y2, Y2
	VPMULLD      Y5, Y2, Y2
	VPADDD       Y2, Y7, Y7
	VPBROADCASTD 64(CX), Y2
	VPADDD       Y2, Y7, Y7
	VPCMPGTD     Y7, Y6, Y2
	VPBLENDVB    Y2, Y7, Y6, Y6
	VPBLENDVB    Y2, Y0, Y10, Y10
	VPBROADCASTD 60(CX), Y2
	VPCMPGTD     Y1, Y2, Y2
	VPBLENDVB    Y2, Y0, Y10, Y10
	VPSLLVD      decodeIdxShiftsHi<>+0(SB), Y10, Y10
	VPOR         Y10, Y11, Y11
	VEXTRACTI128 $0x01, Y11, X0
	VPOR         X0, X11, X11
	VPSHUFD      $0x4e, X11, X0
	VPOR         X0, X11, X11
	VPSHUFD      $0xe5, X11, X0
	VPOR         X0, X11, X11
	VMOVD        X11, AX
	VZEROUPPER
	MOVL         AX, ret+16(FP)
	RET

// func ScoreDXT1PaletteAVX2(block *[64]byte, cc uint32, weights *[4]int32) uint32
// Requires: AVX, AVX2
TEXT ·ScoreDXT1PaletteAVX2(SB), NOSPLIT, $0-28
	MOVQ         block+0(FP), AX
	MOVL         cc+8(FP), CX
	MOVQ         weights+16(FP), DX
	MOVL         CX, BX
	ANDL         $0x0000ffff, BX
	SHRL         $0x10, CX
	VPCMPEQD     Y0, Y0, Y0
	VPSRLD       $0x18, Y0, Y0
	VMOVDQU      (AX), Y1
	VMOVDQU      32(AX), Y2
	VPAND        Y0, Y1, Y3
	VPSRLD       $0x08, Y1, Y4
	VPAND        Y0, Y4, Y4
	VPSRLD       $0x10, Y1, Y1
	VPAND        Y0, Y1, Y1
	VPAND        Y0, Y2, Y5
	VPSRLD       $0x08, Y2, Y6
	VPAND        Y0, Y6, Y6
	VPSRLD       $0x10, Y2, Y2
	VPAND        Y0, Y2, Y2
	VPBROADCASTD (DX), Y0
	VPBROADCASTD 4(DX), Y7
	VPBROADCASTD 8(DX), Y8
	MOVL         BX, AX
	SHRL         $0x0b, AX
	IMUL3Q       $0x0000020f, AX, AX
	ADDL         $0x17, AX
	SHRL         $0x06, AX
	MOVL         BX, DX
	SHRL         $0x05, DX
	ANDL         $0x3f, DX
	IMUL3Q       $0x00000103, DX, DX
	ADDL         $0x21, DX
	SHRL         $0x06, DX
	MOVL         BX, SI
	ANDL         $0x1f, SI
	IMUL3Q       $0x0000020f, SI, SI
	ADDL         $0x17, SI
	SHRL         $0x06, SI
	MOVL         CX, DI
	SHRL         $0x0b, DI
	IMUL3Q       $0x0000020f, DI, DI
	ADDL         $0x17, DI
	SHRL         $0x06, DI
	MOVL         CX, R8
	SHRL         $0x05, R8
	ANDL         $0x3f, R8
	IMUL3Q       $0x00000103, R8, R8
	ADDL         $0x21, R8
	SHRL         $0x06, R8
	MOVL         CX, R9
	ANDL         $0x1f, R9
	IMUL3Q       $0x0000020f, R9, R9
	ADDL         $0x17, R9
	SHRL         $0x06, R9
	VMOVD        AX, X9
	VPBROADCASTD X9, Y10
	VPSUBD       Y10, Y3, Y9
	VPMULLD      Y9, Y9, Y9
	VPMULLD      Y0, Y9, Y9
	VPSUBD       Y10, Y5, Y10
	VPMULLD      Y10, Y10, Y10
	VPMULLD      Y0, Y10, Y10
	VMOVD        DX, X11
	VPBROADCASTD X11, Y11
	VPSUBD       Y11, Y4, Y12
	VPMULLD      Y12, Y12, Y12
	VPMULLD      Y7, Y12, Y12
	VPADDD       Y12, Y9, Y9
	VPSUBD       Y11, Y6, Y11
	VPMULLD      Y11, Y11, Y11
	VPMULLD      Y7, Y11, Y11
	VPADDD       Y11, Y10, Y10
	VMOVD        SI, X11
	VPBROADCASTD X11, Y11
	VPSUBD       Y11, Y1, Y12
	VPMULLD      Y12, Y12, Y12
	VPMULLD      Y8, Y12, Y12
	VPADDD       Y12, Y9, Y9
	VPSUBD       Y11, Y2, Y11
	VPMULLD      Y11, Y11, Y11
	VPMULLD      Y8, Y11, Y11
	VPADDD       Y11, Y10, Y10
	VMOVDQU      Y9, Y9
	VMOVDQU      Y10, Y10
	VMOVD        DI, X11
	VPBROADCASTD X11, Y11
	VPSUBD       Y11, Y3, Y12
	VPMULLD      Y12, Y12, Y12
	VPMULLD      Y0, Y12, Y12
	VPSUBD       Y11, Y5, Y11
	VPMULLD      Y11, Y11, Y11
	VPMULLD      Y0, Y11, Y11
	VMOVD        R8, X13
	VPBROADCASTD X13, Y13
	VPSUBD       Y13, Y4, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y7, Y14, Y14
	VPADDD       Y14, Y12, Y12
	VPSUBD       Y13, Y6, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y7, Y13, Y13
	VPADDD       Y13, Y11, Y11
	VMOVD        R9, X13
	VPBROADCASTD X13, Y13
	VPSUBD       Y13, Y1, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y8, Y14, Y14
	VPADDD       Y14, Y12, Y12
	VPSUBD       Y13, Y2, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y8, Y13, Y13
	VPADDD       Y13, Y11, Y11
	VPMINSD      Y12, Y9, Y9
	VPMINSD      Y11, Y10, Y10
	CMPL         BX, CX
	JHI          mode4
	LEAQ         (AX)(DI*1), AX
	SHRL         $0x01, AX
	LEAQ         (DX)(R8*1), CX
	SHRL         $0x01, CX
	LEAQ         (SI)(R9*1), DX
	SHRL         $0x01, DX
	VMOVD        AX, X11
	VPBROADCASTD X11, Y11
	VPSUBD       Y11, Y3, Y12
	VPMULLD      Y12, Y12, Y12
	VPMULLD      Y0, Y12, Y12
	VPSUBD       Y11, Y5, Y11
	VPMULLD      Y11, Y11, Y11
	VPMULLD      Y0, Y11, Y11
	VMOVD        CX, X13
	VPBROADCASTD X13, Y13
	VPSUBD       Y13, Y4, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y7, Y14, Y14
	VPADDD       Y14, Y12, Y12
	VPSUBD       Y13, Y6, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y7, Y13, Y13
	VPADDD       Y13, Y11, Y11
	VMOVD        DX, X13
	VPBROADCASTD X13, Y13
	VPSUBD       Y13, Y1, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y8, Y14, Y14
	VPADDD       Y14, Y12, Y12
	VPSUBD       Y13, Y2, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y8, Y13, Y13
	VPADDD       Y13, Y11, Y11
	VPMINSD      Y12, Y9, Y9
	VPMINSD      Y11, Y10, Y10
	XORL         AX, AX
	VMOVD        AX, X11
	VPBROADCASTD X11, Y11
	VPSUBD       Y11, Y3, Y3
	VPMULLD      Y3, Y3, Y3
	VPMULLD      Y0, Y3, Y3
	VPSUBD       Y11, Y5, Y5
	VPMULLD      Y5, Y5, Y5
	VPMULLD      Y0, Y5, Y5
	VMOVD        AX, X0
	VPBROADCASTD X0, Y0
	VPSUBD       Y0, Y4, Y4
	VPMULLD      Y4, Y4, Y4
	VPMULLD      Y7, Y4, Y4
	VPADDD       Y4, Y3, Y3
	VPSUBD       Y0, Y6, Y0
	VPMULLD      Y0, Y0, Y0
	VPMULLD      Y7, Y0, Y0
	VPADDD       Y0, Y5, Y5
	VMOVD        AX, X0
	VPBROADCASTD X0, Y0
	VPSUBD       Y0, Y1, Y1
	VPMULLD      Y1, Y1, Y1
	VPMULLD      Y8, Y1, Y1
	VPADDD       Y1, Y3, Y3
	VPSUBD       Y0, Y2, Y0
	VPMULLD      Y0, Y0, Y0
	VPMULLD      Y8, Y0, Y0
	VPADDD       Y0, Y5, Y5
	VPMINSD      Y3, Y9, Y9
	VPMINSD      Y5, Y10, Y10
	JMP          reduce

mode4:
	LEAQ         1(DI)(AX*2), CX
	IMUL3Q       $0x000002ab, CX, CX
	SHRL         $0x0b, CX
	LEAQ         1(R8)(DX*2), BX
	IMUL3Q       $0x000002ab, BX, BX
	SHRL         $0x0b, BX
	LEAQ         1(R9)(SI*2), R10
	IMUL3Q       $0x000002ab, R10, R10
	SHRL         $0x0b, R10
	VMOVD        CX, X11
	VPBROADCASTD X11, Y11
	VPSUBD       Y11, Y3, Y12
	VPMULLD      Y12, Y12, Y12
	VPMULLD      Y0, Y12, Y12
	VPSUBD       Y11, Y5, Y11
	VPMULLD      Y11, Y11, Y11
	VPMULLD      Y0, Y11, Y11
	VMOVD        BX, X13
	VPBROADCASTD X13, Y13
	VPSUBD       Y13, Y4, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y7, Y14, Y14
	VPADDD       Y14, Y12, Y12
	VPSUBD       Y13, Y6, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y7, Y13, Y13
	VPADDD       Y13, Y11, Y11
	VMOVD        R10, X13
	VPBROADCASTD X13, Y13
	VPSUBD       Y13, Y1, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y8, Y14, Y14
	VPADDD       Y14, Y12, Y12
	VPSUBD       Y13, Y2, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y8, Y13, Y13
	VPADDD       Y13, Y11, Y11
	VPMINSD      Y12, Y9, Y9
	VPMINSD      Y11, Y10, Y10
	LEAQ         1(AX)(DI*2), AX
	IMUL3Q       $0x000002ab, AX, AX
	SHRL         $0x0b, AX
	LEAQ         1(DX)(R8*2), CX
	IMUL3Q       $0x000002ab, CX, CX
	SHRL         $0x0b, CX
	LEAQ         1(SI)(R9*2), DX
	IMUL3Q       $0x000002ab, DX, DX
	SHRL         $0x0b, DX
	VMOVD        AX, X11
	VPBROADCASTD X11, Y11
	VPSUBD       Y11, Y3, Y3
	VPMULLD      Y3, Y3, Y3
	VPMULLD      Y0, Y3, Y3
	VPSUBD       Y11, Y5, Y5
	VPMULLD      Y5, Y5, Y5
	VPMULLD      Y0, Y5, Y5
	VMOVD        CX, X0
	VPBROADCASTD X0, Y0
	VPSUBD       Y0, Y4, Y4
	VPMULLD      Y4, Y4, Y4
	VPMULLD      Y7, Y4, Y4
	VPADDD       Y4, Y3, Y3
	VPSUBD       Y0, Y6, Y0
	VPMULLD      Y0, Y0, Y0
	VPMULLD      Y7, Y0, Y0
	VPADDD       Y0, Y5, Y5
	VMOVD        DX, X0
	VPBROADCASTD X0, Y0
	VPSUBD       Y0, Y1, Y1
	VPMULLD      Y1, Y1, Y1
	VPMULLD      Y8, Y1, Y1
	VPADDD       Y1, Y3, Y3
	VPSUBD       Y0, Y2, Y0
	VPMULLD      Y0, Y0, Y0
	VPMULLD      Y8, Y0, Y0
	VPADDD       Y0, Y5, Y5
	VPMINSD      Y3, Y9, Y9
	VPMINSD      Y5, Y10, Y10

reduce:
	VPADDD       Y10, Y9, Y0
	VEXTRACTI128 $0x01, Y0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0x4e, X0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0xe5, X0, X1
	VPADDD       X1, X0, X0
	VMOVD        X0, AX
	VZEROUPPER
	MOVL         AX, ret+24(FP)
	RET

DATA alphaIdxShifts<>+0(SB)/4, $0x00000000
DATA alphaIdxShifts<>+4(SB)/4, $0x00000003
DATA alphaIdxShifts<>+8(SB)/4, $0x00000006
DATA alphaIdxShifts<>+12(SB)/4, $0x00000009
DATA alphaIdxShifts<>+16(SB)/4, $0x0000000c
DATA alphaIdxShifts<>+20(SB)/4, $0x0000000f
DATA alphaIdxShifts<>+24(SB)/4, $0x00000012
DATA alphaIdxShifts<>+28(SB)/4, $0x00000015
GLOBL alphaIdxShifts<>(SB), RODATA|NOPTR, $32

// func AlphaBlockErrorAVX2(samples *[16]uint8, aa uint32) uint32
// Requires: AVX, AVX2, CMOV
TEXT ·AlphaBlockErrorAVX2(SB), NOSPLIT, $32-20
	MOVQ         samples+0(FP), AX
	MOVL         aa+8(FP), CX
	MOVL         CX, DX
	ANDL         $0x000000ff, DX
	SHRL         $0x08, CX
	ANDL         $0x000000ff, CX
	LEAQ         decodeAlphaPalConsts<>+64(SB), BX
	LEAQ         decodeAlphaPalConsts<>+0(SB), SI
	CMPL         DX, CX
	CMOVQHI      SI, BX
	VMOVD        DX, X0
	VPBROADCASTW X0, X0
	VMOVD        CX, X1
	VPBROADCASTW X1, X1
	VPMULLW      (BX), X0, X0
	VPMULLW      16(BX), X1, X1
	VPADDW       X1, X0, X0
	VPADDW       32(BX), X0, X0
	VPMULHUW     48(BX), X0, X0
	VPMOVZXWD    X0, Y0
	VMOVDQU      Y0, (SP)
	VPMOVZXBD    (AX), Y0
	VPMOVZXBD    8(AX), Y1
	VPBROADCASTD (SP), Y2
	VPSUBD       Y2, Y0, Y3
	VPMULLD      Y3, Y3, Y3
	VPSUBD       Y2, Y1, Y2
	VPMULLD      Y2, Y2, Y2
	VPBROADCASTD 4(SP), Y4
	VPSUBD       Y4, Y0, Y5
	VPMULLD      Y5, Y5, Y5
	VPMINSD      Y5, Y3, Y3
	VPSUBD       Y4, Y1, Y4
	VPMULLD      Y4, Y4, Y4
	VPMINSD      Y4, Y2, Y2
	VPBROADCASTD 8(SP), Y4
	VPSUBD       Y4, Y0, Y5
	VPMULLD      Y5, Y5, Y5
	VPMINSD      Y5, Y3, Y3
	VPSUBD       Y4, Y1, Y4
	VPMULLD      Y4, Y4, Y4
	VPMINSD      Y4, Y2, Y2
	VPBROADCASTD 12(SP), Y4
	VPSUBD       Y4, Y0, Y5
	VPMULLD      Y5, Y5, Y5
	VPMINSD      Y5, Y3, Y3
	VPSUBD       Y4, Y1, Y4
	VPMULLD      Y4, Y4, Y4
	VPMINSD      Y4, Y2, Y2
	VPBROADCASTD 16(SP), Y4
	VPSUBD       Y4, Y0, Y5
	VPMULLD      Y5, Y5, Y5
	VPMINSD      Y5, Y3, Y3
	VPSUBD       Y4, Y1, Y4
	VPMULLD      Y4, Y4, Y4
	VPMINSD      Y4, Y2, Y2
	VPBROADCASTD 20(SP), Y4
	VPSUBD       Y4, Y0, Y5
	VPMULLD      Y5, Y5, Y5
	VPMINSD      Y5, Y3, Y3
	VPSUBD       Y4, Y1, Y4
	VPMULLD      Y4, Y4, Y4
	VPMINSD      Y4, Y2, Y2
	VPBROADCASTD 24(SP), Y4
	VPSUBD       Y4, Y0, Y5
	VPMULLD      Y5, Y5, Y5
	VPMINSD      Y5, Y3, Y3
	VPSUBD       Y4, Y1, Y4
	VPMULLD      Y4, Y4, Y4
	VPMINSD      Y4, Y2, Y2
	VPBROADCASTD 28(SP), Y4
	VPSUBD       Y4, Y0, Y0
	VPMULLD      Y0, Y0, Y0
	VPMINSD      Y0, Y3, Y3
	VPSUBD       Y4, Y1, Y0
	VPMULLD      Y0, Y0, Y0
	VPMINSD      Y0, Y2, Y2
	VPADDD       Y2, Y3, Y0
	VEXTRACTI128 $0x01, Y0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0x4e, X0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0xe5, X0, X1
	VPADDD       X1, X0, X0
	VMOVD        X0, AX
	VZEROUPPER
	MOVL         AX, ret+16(FP)
	RET

// func BestAlphaIndices16AVX2(samples *[16]uint8, aa uint32) uint64
// Requires: AVX, AVX2, CMOV
TEXT ·BestAlphaIndices16AVX2(SB), NOSPLIT, $32-24
	MOVQ         samples+0(FP), AX
	MOVL         aa+8(FP), CX
	MOVL         CX, DX
	ANDL         $0x000000ff, DX
	SHRL         $0x08, CX
	ANDL         $0x000000ff, CX
	LEAQ         decodeAlphaPalConsts<>+64(SB), BX
	LEAQ         decodeAlphaPalConsts<>+0(SB), SI
	CMPL         DX, CX
	CMOVQHI      SI, BX
	VMOVD        DX, X0
	VPBROADCASTW X0, X0
	VMOVD        CX, X1
	VPBROADCASTW X1, X1
	VPMULLW      (BX), X0, X0
	VPMULLW      16(BX), X1, X1
	VPADDW       X1, X0, X0
	VPADDW       32(BX), X0, X0
	VPMULHUW     48(BX), X0, X0
	VPMOVZXWD    X0, Y0
	VMOVDQU      Y0, (SP)
	VPMOVZXBD    (AX), Y0
	VPMOVZXBD    8(AX), Y1
	VPCMPEQD     Y2, Y2, Y2
	VPSRLD       $0x1f, Y2, Y2
	VPBROADCASTD (SP), Y3
	VPSUBD       Y3, Y0, Y4
	VPMULLD      Y4, Y4, Y4
	VPSUBD       Y3, Y1, Y3
	VPMULLD      Y3, Y3, Y3
	VPXOR        Y5, Y5, Y5
	VPXOR        Y6, Y6, Y6
	VMOVDQU      Y2, Y7
	VPBROADCASTD 4(SP), Y8
	VPSUBD       Y8, Y0, Y9
	VPMULLD      Y9, Y9, Y9
	VPCMPGTD     Y9, Y4, Y10
	VPBLENDVB    Y10, Y9, Y4, Y4
	VPBLENDVB    Y10, Y7, Y5, Y5
	VPSUBD       Y8, Y1, Y8
	VPMULLD      Y8, Y8, Y8
	VPCMPGTD     Y8, Y3, Y9
	VPBLENDVB    Y9, Y8, Y3, Y3
	VPBLENDVB    Y9, Y7, Y6, Y6
	VPADDD       Y2, Y7, Y7
	VPBROADCASTD 8(SP), Y8
	VPSUBD       Y8, Y0, Y9
	VPMULLD      Y9, Y9, Y9
	VPCMPGTD     Y9, Y4, Y10
	VPBLENDVB    Y10, Y9, Y4, Y4
	VPBLENDVB    Y10, Y7, Y5, Y5
	VPSUBD       Y8, Y1, Y8
	VPMULLD      Y8, Y8, Y8
	VPCMPGTD     Y8, Y3, Y9
	VPBLENDVB    Y9, Y8, Y3, Y3
	VPBLENDVB    Y9, Y7, Y6, Y6
	VPADDD       Y2, Y7, Y7
	VPBROADCASTD 12(SP), Y8
	VPSUBD       Y8, Y0, Y9
	VPMULLD      Y9, Y9, Y9
	VPCMPGTD     Y9, Y4, Y10
	VPBLENDVB    Y10, Y9, Y4, Y4
	VPBLENDVB    Y10, Y7, Y5, Y5
	VPSUBD       Y8, Y1, Y8
	VPMULLD      Y8, Y8, Y8
	VPCMPGTD     Y8, Y3, Y9
	VPBLENDVB    Y9, Y8, Y3, Y3
	VPBLENDVB    Y9, Y7, Y6, Y6
	VPADDD       Y2, Y7, Y7
	VPBROADCASTD 16(SP), Y8
	VPSUBD       Y8, Y0, Y9
	VPMULLD      Y9, Y9, Y9
	VPCMPGTD     Y9, Y4, Y10
	VPBLENDVB    Y10, Y9, Y4, Y4
	VPBLENDVB    Y10, Y7, Y5, Y5
	VPSUBD       Y8, Y1, Y8
	VPMULLD      Y8, Y8, Y8
	VPCMPGTD     Y8, Y3, Y9
	VPBLENDVB    Y9, Y8, Y3, Y3
	VPBLENDVB    Y9, Y7, Y6, Y6
	VPADDD       Y2, Y7, Y7
	VPBROADCASTD 20(SP), Y8
	VPSUBD       Y8, Y0, Y9
	VPMULLD      Y9, Y9, Y9
	VPCMPGTD     Y9, Y4, Y10
	VPBLENDVB    Y10, Y9, Y4, Y4
	VPBLENDVB    Y10, Y7, Y5, Y5
	VPSUBD       Y8, Y1, Y8
	VPMULLD      Y8, Y8, Y8
	VPCMPGTD     Y8, Y3, Y9
	VPBLENDVB    Y9, Y8, Y3, Y3
	VPBLENDVB    Y9, Y7, Y6, Y6
	VPADDD       Y2, Y7, Y7
	VPBROADCASTD 24(SP), Y8
	VPSUBD       Y8, Y0, Y9
	VPMULLD      Y9, Y9, Y9
	VPCMPGTD     Y9, Y4, Y10
	VPBLENDVB    Y10, Y9, Y4, Y4
	VPBLENDVB    Y10, Y7, Y5, Y5
	VPSUBD       Y8, Y1, Y8
	VPMULLD      Y8, Y8, Y8
	VPCMPGTD     Y8, Y3, Y9
	VPBLENDVB    Y9, Y8, Y3, Y3
	VPBLENDVB    Y9, Y7, Y6, Y6
	VPADDD       Y2, Y7, Y7
	VPBROADCASTD 28(SP), Y2
	VPSUBD       Y2, Y0, Y0
	VPMULLD      Y0, Y0, Y0
	VPCMPGTD     Y0, Y4, Y8
	VPBLENDVB    Y8, Y0, Y4, Y4
	VPBLENDVB    Y8, Y7, Y5, Y5
	VPSUBD       Y2, Y1, Y0
	VPMULLD      Y0, Y0, Y0
	VPCMPGTD     Y0, Y3, Y1
	VPBLENDVB    Y1, Y0, Y3, Y3
	VPBLENDVB    Y1, Y7, Y6, Y6
	VMOVDQU      alphaIdxShifts<>+0(SB), Y0
	VPSLLVD      Y0, Y5, Y5
	VPSLLVD      Y0, Y6, Y6
	VEXTRACTI128 $0x01, Y5, X0
	VPOR         X0, X5, X5
	VPSHUFD      $0x4e, X5, X0
	VPOR         X0, X5, X5
	VPSHUFD      $0xe5, X5, X0
	VPOR         X0, X5, X5
	VMOVD        X5, AX
	VEXTRACTI128 $0x01, Y6, X0
	VPOR         X0, X6, X6
	VPSHUFD      $0x4e, X6, X0
	VPOR         X0, X6, X6
	VPSHUFD      $0xe5, X6, X0
	VPOR         X0, X6, X6
	VMOVD        X6, CX
	MOVL         CX, CX
	SHLQ         $0x18, CX
	ORQ          CX, AX
	MOVQ         AX, ret+16(FP)
	RET

// func LSQColorAccumulateAVX2(block *[64]byte, params *[22]int32, out *[9]int32)
// Requires: AVX, AVX2
TEXT ·LSQColorAccumulateAVX2(SB), NOSPLIT, $0-24
	MOVQ         block+0(FP), AX
	MOVQ         params+8(FP), CX
	MOVQ         out+16(FP), DX
	VPCMPEQD     Y0, Y0, Y0
	VPSRLD       $0x18, Y0, Y1
	VPSRLD       $0x1f, Y0, Y0
	VPSLLD       $0x01, Y0, Y2
	VPADDD       Y0, Y2, Y3
	VPXOR        Y4, Y4, Y4
	VPBROADCASTD 48(CX), Y5
	VPBROADCASTD 52(CX), Y6
	VPBROADCASTD 56(CX), Y7
	VMOVDQU      (AX), Y8
	VPAND        Y1, Y8, Y9
	VPSRLD       $0x08, Y8, Y10
	VPAND        Y1, Y10, Y10
	VPSRLD       $0x10, Y8, Y11
	VPAND        Y1, Y11, Y11
	VPSRLD       $0x18, Y8, Y8
	VPBROADCASTD (CX), Y13
	VPSUBD       Y13, Y9, Y12
	VPMULLD      Y12, Y12, Y12
	VPMULLD      Y5, Y12, Y12
	VPBROADCASTD 16(CX), Y13
	VPSUBD       Y13, Y10, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y6, Y13, Y13
	VPADDD       Y13, Y12, Y12
	VPBROADCASTD 32(CX), Y13
	VPSUBD       Y13, Y11, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y7, Y13, Y13
	VPADDD       Y13, Y12, Y12
	VPXOR        Y13, Y13, Y13
	VPBROADCASTD 4(CX), Y15
	VPSUBD       Y15, Y9, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y5, Y14, Y14
	VPBROADCASTD 20(CX), Y15
	VPSUBD       Y15, Y10, Y15
	VPMULLD      Y15, Y15, Y15
	VPMULLD      Y6, Y15, Y15
	VPADDD       Y15, Y14, Y14
	VPBROADCASTD 36(CX), Y15
	VPSUBD       Y15, Y11, Y15
	VPMULLD      Y15, Y15, Y15
	VPMULLD      Y7, Y15, Y15
	VPADDD       Y15, Y14, Y14
	VPCMPGTD     Y14, Y12, Y15
	VPBLENDVB    Y15, Y14, Y12, Y12
	VPBLENDVB    Y15, Y0, Y13, Y13
	VPBROADCASTD 8(CX), Y15
	VPSUBD       Y15, Y9, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y5, Y14, Y14
	VPBROADCASTD 24(CX), Y15
	VPSUBD       Y15, Y10, Y15
	VPMULLD      Y15, Y15, Y15
	VPMULLD      Y6, Y15, Y15
	VPADDD       Y15, Y14, Y14
	VPBROADCASTD 40(CX), Y15
	VPSUBD       Y15, Y11, Y15
	VPMULLD      Y15, Y15, Y15
	VPMULLD      Y7, Y15, Y15
	VPADDD       Y15, Y14, Y14
	VPCMPGTD     Y14, Y12, Y15
	VPBLENDVB    Y15, Y14, Y12, Y12
	VPBLENDVB    Y15, Y2, Y13, Y13
	VPBROADCASTD 12(CX), Y15
	VPSUBD       Y15, Y9, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y5, Y14, Y14
	VPBROADCASTD 28(CX), Y15
	VPSUBD       Y15, Y10, Y15
	VPMULLD      Y15, Y15, Y15
	VPMULLD      Y6, Y15, Y15
	VPADDD       Y15, Y14, Y14
	VPBROADCASTD 44(CX), Y15
	VPSUBD       Y15, Y11, Y15
	VPMULLD      Y15, Y15, Y15
	VPMULLD      Y7, Y15, Y15
	VPADDD       Y15, Y14, Y14
	VPBROADCASTD 64(CX), Y15
	VPADDD       Y15, Y14, Y14
	VPCMPGTD     Y14, Y12, Y15
	VPBLENDVB    Y15, Y14, Y12, Y12
	VPBLENDVB    Y15, Y3, Y13, Y13
	VPXOR        Y12, Y12, Y12
	VPBROADCASTD 76(CX), Y14
	VMOVDQU      Y0, Y15
	VPCMPEQD     Y15, Y13, Y15
	VPBLENDVB    Y15, Y14, Y12, Y12
	VPBROADCASTD 80(CX), Y14
	VMOVDQU      Y2, Y15
	VPCMPEQD     Y15, Y13, Y15
	VPBLENDVB    Y15, Y14, Y12, Y12
	VPBROADCASTD 84(CX), Y14
	VMOVDQU      Y3, Y15
	VPCMPEQD     Y15, Y13, Y13
	VPBLENDVB    Y13, Y14, Y12, Y12
	VPBROADCASTD 68(CX), Y13
	VPSUBD       Y12, Y13, Y13
	VPBROADCASTD 60(CX), Y14
	VPCMPGTD     Y8, Y14, Y8
	VPBLENDVB    Y8, Y4, Y13, Y13
	VPBLENDVB    Y8, Y4, Y12, Y12
	VMOVDQU      Y13, Y8
	VPMULLD      Y13, Y8, Y8
	VEXTRACTI128 $0x01, Y8, X14
	VPADDD       X14, X8, X8
	VPSHUFD      $0x4e, X8, X14
	VPADDD       X14, X8, X8
	VPSHUFD      $0xe5, X8, X14
	VPADDD       X14, X8, X8
	VMOVD        X8, BX
	MOVL         BX, (DX)
	VMOVDQU      Y12, Y8
	VPMULLD      Y12, Y8, Y8
	VEXTRACTI128 $0x01, Y8, X14
	VPADDD       X14, X8, X8
	VPSHUFD      $0x4e, X8, X14
	VPADDD       X14, X8, X8
	VPSHUFD      $0xe5, X8, X14
	VPADDD       X14, X8, X8
	VMOVD        X8, BX
	MOVL         BX, 4(DX)
	VMOVDQU      Y13, Y8
	VPMULLD      Y12, Y8, Y8
	VEXTRACTI128 $0x01, Y8, X14
	VPADDD       X14, X8, X8
	VPSHUFD      $0x4e, X8, X14
	VPADDD       X14, X8, X8
	VPSHUFD      $0xe5, X8, X14
	VPADDD       X14, X8, X8
	VMOVD        X8, BX
	MOVL         BX, 8(DX)
	VMOVDQU      Y13, Y8
	VPMULLD      Y9, Y8, Y8
	VEXTRACTI128 $0x01, Y8, X14
	VPADDD       X14, X8, X8
	VPSHUFD      $0x4e, X8, X14
	VPADDD       X14, X8, X8
	VPSHUFD      $0xe5, X8, X14
	VPADDD       X14, X8, X8
	VMOVD        X8, BX
	MOVL         BX, 12(DX)
	VMOVDQU      Y13, Y8
	VPMULLD      Y10, Y8, Y8
	VEXTRACTI128 $0x01, Y8, X14
	VPADDD       X14, X8, X8
	VPSHUFD      $0x4e, X8, X14
	VPADDD       X14, X8, X8
	VPSHUFD      $0xe5, X8, X14
	VPADDD       X14, X8, X8
	VMOVD        X8, BX
	MOVL         BX, 16(DX)
	VMOVDQU      Y13, Y8
	VPMULLD      Y11, Y8, Y8
	VEXTRACTI128 $0x01, Y8, X13
	VPADDD       X13, X8, X8
	VPSHUFD      $0x4e, X8, X13
	VPADDD       X13, X8, X8
	VPSHUFD      $0xe5, X8, X13
	VPADDD       X13, X8, X8
	VMOVD        X8, BX
	MOVL         BX, 20(DX)
	VMOVDQU      Y12, Y8
	VPMULLD      Y9, Y8, Y8
	VEXTRACTI128 $0x01, Y8, X9
	VPADDD       X9, X8, X8
	VPSHUFD      $0x4e, X8, X9
	VPADDD       X9, X8, X8
	VPSHUFD      $0xe5, X8, X9
	VPADDD       X9, X8, X8
	VMOVD        X8, BX
	MOVL         BX, 24(DX)
	VMOVDQU      Y12, Y8
	VPMULLD      Y10, Y8, Y8
	VEXTRACTI128 $0x01, Y8, X9
	VPADDD       X9, X8, X8
	VPSHUFD      $0x4e, X8, X9
	VPADDD       X9, X8, X8
	VPSHUFD      $0xe5, X8, X9
	VPADDD       X9, X8, X8
	VMOVD        X8, BX
	MOVL         BX, 28(DX)
	VMOVDQU      Y12, Y8
	VPMULLD      Y11, Y8, Y8
	VEXTRACTI128 $0x01, Y8, X9
	VPADDD       X9, X8, X8
	VPSHUFD      $0x4e, X8, X9
	VPADDD       X9, X8, X8
	VPSHUFD      $0xe5, X8, X9
	VPADDD       X9, X8, X8
	VMOVD        X8, BX
	MOVL         BX, 32(DX)
	VMOVDQU      32(AX), Y8
	VPAND        Y1, Y8, Y9
	VPSRLD       $0x08, Y8, Y10
	VPAND        Y1, Y10, Y10
	VPSRLD       $0x10, Y8, Y11
	VPAND        Y1, Y11, Y11
	VPSRLD       $0x18, Y8, Y1
	VPBROADCASTD (CX), Y12
	VPSUBD       Y12, Y9, Y8
	VPMULLD      Y8, Y8, Y8
	VPMULLD      Y5, Y8, Y8
	VPBROADCASTD 16(CX), Y12
	VPSUBD       Y12, Y10, Y12
	VPMULLD      Y12, Y12, Y12
	VPMULLD      Y6, Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPBROADCASTD 32(CX), Y12
	VPSUBD       Y12, Y11, Y12
	VPMULLD      Y12, Y12, Y12
	VPMULLD      Y7, Y12, Y12
	VPADDD       Y12, Y8, Y8
	VPXOR        Y12, Y12, Y12
	VPBROADCASTD 4(CX), Y14
	VPSUBD       Y14, Y9, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y5, Y13, Y13
	VPBROADCASTD 20(CX), Y14
	VPSUBD       Y14, Y10, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y6, Y14, Y14
	VPADDD       Y14, Y13, Y13
	VPBROADCASTD 36(CX), Y14
	VPSUBD       Y14, Y11, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y7, Y14, Y14
	VPADDD       Y14, Y13, Y13
	VPCMPGTD     Y13, Y8, Y14
	VPBLENDVB    Y14, Y13, Y8, Y8
	VPBLENDVB    Y14, Y0, Y12, Y12
	VPBROADCASTD 8(CX), Y14
	VPSUBD       Y14, Y9, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y5, Y13, Y13
	VPBROADCASTD 24(CX), Y14
	VPSUBD       Y14, Y10, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y6, Y14, Y14
	VPADDD       Y14, Y13, Y13
	VPBROADCASTD 40(CX), Y14
	VPSUBD       Y14, Y11, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y7, Y14, Y14
	VPADDD       Y14, Y13, Y13
	VPCMPGTD     Y13, Y8, Y14
	VPBLENDVB    Y14, Y13, Y8, Y8
	VPBLENDVB    Y14, Y2, Y12, Y12
	VPBROADCASTD 12(CX), Y14
	VPSUBD       Y14, Y9, Y13
	VPMULLD      Y13, Y13, Y13
	VPMULLD      Y5, Y13, Y13
	VPBROADCASTD 28(CX), Y14
	VPSUBD       Y14, Y10, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y6, Y14, Y14
	VPADDD       Y14, Y13, Y13
	VPBROADCASTD 44(CX), Y14
	VPSUBD       Y14, Y11, Y14
	VPMULLD      Y14, Y14, Y14
	VPMULLD      Y7, Y14, Y14
	VPADDD       Y14, Y13, Y13
	VPBROADCASTD 64(CX), Y5
	VPADDD       Y5, Y13, Y13
	VPCMPGTD     Y13, Y8, Y5
	VPBLENDVB    Y5, Y13, Y8, Y8
	VPBLENDVB    Y5, Y3, Y12, Y12
	VPXOR        Y5, Y5, Y5
	VPBROADCASTD 76(CX), Y6
	VMOVDQU      Y0, Y0
	VPCMPEQD     Y0, Y12, Y0
	VPBLENDVB    Y0, Y6, Y5, Y5
	VPBROADCASTD 80(CX), Y0
	VMOVDQU      Y2, Y2
	VPCMPEQD     Y2, Y12, Y2
	VPBLENDVB    Y2, Y0, Y5, Y5
	VPBROADCASTD 84(CX), Y0
	VMOVDQU      Y3, Y2
	VPCMPEQD     Y2, Y12, Y2
	VPBLENDVB    Y2, Y0, Y5, Y5
	VPBROADCASTD 68(CX), Y0
	VPSUBD       Y5, Y0, Y0
	VPBROADCASTD 60(CX), Y2
	VPCMPGTD     Y1, Y2, Y1
	VPBLENDVB    Y1, Y4, Y0, Y0
	VPBLENDVB    Y1, Y4, Y5, Y5
	VMOVDQU      Y0, Y1
	VPMULLD      Y0, Y1, Y1
	VEXTRACTI128 $0x01, Y1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0x4e, X1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0xe5, X1, X2
	VPADDD       X2, X1, X1
	VMOVD        X1, AX
	ADDL         AX, (DX)
	VMOVDQU      Y5, Y1
	VPMULLD      Y5, Y1, Y1
	VEXTRACTI128 $0x01, Y1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0x4e, X1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0xe5, X1, X2
	VPADDD       X2, X1, X1
	VMOVD        X1, AX
	ADDL         AX, 4(DX)
	VMOVDQU      Y0, Y1
	VPMULLD      Y5, Y1, Y1
	VEXTRACTI128 $0x01, Y1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0x4e, X1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0xe5, X1, X2
	VPADDD       X2, X1, X1
	VMOVD        X1, AX
	ADDL         AX, 8(DX)
	VMOVDQU      Y0, Y1
	VPMULLD      Y9, Y1, Y1
	VEXTRACTI128 $0x01, Y1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0x4e, X1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0xe5, X1, X2
	VPADDD       X2, X1, X1
	VMOVD        X1, AX
	ADDL         AX, 12(DX)
	VMOVDQU      Y0, Y1
	VPMULLD      Y10, Y1, Y1
	VEXTRACTI128 $0x01, Y1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0x4e, X1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0xe5, X1, X2
	VPADDD       X2, X1, X1
	VMOVD        X1, AX
	ADDL         AX, 16(DX)
	VMOVDQU      Y0, Y0
	VPMULLD      Y11, Y0, Y0
	VEXTRACTI128 $0x01, Y0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0x4e, X0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0xe5, X0, X1
	VPADDD       X1, X0, X0
	VMOVD        X0, AX
	ADDL         AX, 20(DX)
	VMOVDQU      Y5, Y0
	VPMULLD      Y9, Y0, Y0
	VEXTRACTI128 $0x01, Y0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0x4e, X0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0xe5, X0, X1
	VPADDD       X1, X0, X0
	VMOVD        X0, AX
	ADDL         AX, 24(DX)
	VMOVDQU      Y5, Y0
	VPMULLD      Y10, Y0, Y0
	VEXTRACTI128 $0x01, Y0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0x4e, X0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0xe5, X0, X1
	VPADDD       X1, X0, X0
	VMOVD        X0, AX
	ADDL         AX, 28(DX)
	VMOVDQU      Y5, Y0
	VPMULLD      Y11, Y0, Y0
	VEXTRACTI128 $0x01, Y0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0x4e, X0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0xe5, X0, X1
	VPADDD       X1, X0, X0
	VMOVD        X0, AX
	ADDL         AX, 32(DX)
	VZEROUPPER
	RET

// func LSQAlphaAccumulateAVX2(samples *[16]uint8, aa uint32, out *[5]int32)
// Requires: AVX, AVX2, CMOV
TEXT ·LSQAlphaAccumulateAVX2(SB), NOSPLIT, $32-24
	MOVQ         samples+0(FP), AX
	MOVL         aa+8(FP), CX
	MOVQ         out+16(FP), DX
	MOVL         CX, BX
	ANDL         $0x000000ff, BX
	SHRL         $0x08, CX
	ANDL         $0x000000ff, CX
	LEAQ         decodeAlphaPalConsts<>+64(SB), SI
	LEAQ         decodeAlphaPalConsts<>+0(SB), DI
	CMPL         BX, CX
	CMOVQHI      DI, SI
	VMOVD        BX, X0
	VPBROADCASTW X0, X0
	VMOVD        CX, X1
	VPBROADCASTW X1, X1
	VPMULLW      (SI), X0, X0
	VPMULLW      16(SI), X1, X1
	VPADDW       X1, X0, X0
	VPADDW       32(SI), X0, X0
	VPMULHUW     48(SI), X0, X0
	VPMOVZXWD    X0, Y0
	VMOVDQU      Y0, (SP)
	VPCMPEQD     Y0, Y0, Y0
	VPSRLD       $0x1f, Y0, Y0
	VPXOR        Y1, Y1, Y1
	VPSLLD       $0x03, Y0, Y2
	VPSUBD       Y0, Y2, Y2
	VPMOVZXBD    (AX), Y3
	VPBROADCASTD (SP), Y4
	VPSUBD       Y4, Y3, Y4
	VPMULLD      Y4, Y4, Y4
	VPXOR        Y5, Y5, Y5
	VMOVDQU      Y0, Y6
	VPBROADCASTD 4(SP), Y7
	VPSUBD       Y7, Y3, Y7
	VPMULLD      Y7, Y7, Y7
	VPCMPGTD     Y7, Y4, Y8
	VPBLENDVB    Y8, Y7, Y4, Y4
	VPBLENDVB    Y8, Y6, Y5, Y5
	VPADDD       Y0, Y6, Y6
	VPBROADCASTD 8(SP), Y7
	VPSUBD       Y7, Y3, Y7
	VPMULLD      Y7, Y7, Y7
	VPCMPGTD     Y7, Y4, Y8
	VPBLENDVB    Y8, Y7, Y4, Y4
	VPBLENDVB    Y8, Y6, Y5, Y5
	VPADDD       Y0, Y6, Y6
	VPBROADCASTD 12(SP), Y7
	VPSUBD       Y7, Y3, Y7
	VPMULLD      Y7, Y7, Y7
	VPCMPGTD     Y7, Y4, Y8
	VPBLENDVB    Y8, Y7, Y4, Y4
	VPBLENDVB    Y8, Y6, Y5, Y5
	VPADDD       Y0, Y6, Y6
	VPBROADCASTD 16(SP), Y7
	VPSUBD       Y7, Y3, Y7
	VPMULLD      Y7, Y7, Y7
	VPCMPGTD     Y7, Y4, Y8
	VPBLENDVB    Y8, Y7, Y4, Y4
	VPBLENDVB    Y8, Y6, Y5, Y5
	VPADDD       Y0, Y6, Y6
	VPBROADCASTD 20(SP), Y7
	VPSUBD       Y7, Y3, Y7
	VPMULLD      Y7, Y7, Y7
	VPCMPGTD     Y7, Y4, Y8
	VPBLENDVB    Y8, Y7, Y4, Y4
	VPBLENDVB    Y8, Y6, Y5, Y5
	VPADDD       Y0, Y6, Y6
	VPBROADCASTD 24(SP), Y7
	VPSUBD       Y7, Y3, Y7
	VPMULLD      Y7, Y7, Y7
	VPCMPGTD     Y7, Y4, Y8
	VPBLENDVB    Y8, Y7, Y4, Y4
	VPBLENDVB    Y8, Y6, Y5, Y5
	VPADDD       Y0, Y6, Y6
	VPBROADCASTD 28(SP), Y7
	VPSUBD       Y7, Y3, Y7
	VPMULLD      Y7, Y7, Y7
	VPCMPGTD     Y7, Y4, Y8
	VPBLENDVB    Y8, Y7, Y4, Y4
	VPBLENDVB    Y8, Y6, Y5, Y5
	VPSUBD       Y0, Y5, Y4
	VPCMPEQD     Y1, Y5, Y6
	VPBLENDVB    Y6, Y1, Y4, Y4
	VPCMPEQD     Y0, Y5, Y5
	VPBLENDVB    Y5, Y2, Y4, Y4
	VPSUBD       Y4, Y2, Y5
	VMOVDQU      Y5, Y6
	VPMULLD      Y5, Y6, Y6
	VEXTRACTI128 $0x01, Y6, X7
	VPADDD       X7, X6, X6
	VPSHUFD      $0x4e, X6, X7
	VPADDD       X7, X6, X6
	VPSHUFD      $0xe5, X6, X7
	VPADDD       X7, X6, X6
	VMOVD        X6, CX
	MOVL         CX, (DX)
	VMOVDQU      Y4, Y6
	VPMULLD      Y4, Y6, Y6
	VEXTRACTI128 $0x01, Y6, X7
	VPADDD       X7, X6, X6
	VPSHUFD      $0x4e, X6, X7
	VPADDD       X7, X6, X6
	VPSHUFD      $0xe5, X6, X7
	VPADDD       X7, X6, X6
	VMOVD        X6, CX
	MOVL         CX, 4(DX)
	VMOVDQU      Y5, Y6
	VPMULLD      Y4, Y6, Y6
	VEXTRACTI128 $0x01, Y6, X7
	VPADDD       X7, X6, X6
	VPSHUFD      $0x4e, X6, X7
	VPADDD       X7, X6, X6
	VPSHUFD      $0xe5, X6, X7
	VPADDD       X7, X6, X6
	VMOVD        X6, CX
	MOVL         CX, 8(DX)
	VMOVDQU      Y5, Y5
	VPMULLD      Y3, Y5, Y5
	VEXTRACTI128 $0x01, Y5, X6
	VPADDD       X6, X5, X5
	VPSHUFD      $0x4e, X5, X6
	VPADDD       X6, X5, X5
	VPSHUFD      $0xe5, X5, X6
	VPADDD       X6, X5, X5
	VMOVD        X5, CX
	MOVL         CX, 12(DX)
	VMOVDQU      Y4, Y4
	VPMULLD      Y3, Y4, Y4
	VEXTRACTI128 $0x01, Y4, X3
	VPADDD       X3, X4, X4
	VPSHUFD      $0x4e, X4, X3
	VPADDD       X3, X4, X4
	VPSHUFD      $0xe5, X4, X3
	VPADDD       X3, X4, X4
	VMOVD        X4, CX
	MOVL         CX, 16(DX)
	VPMOVZXBD    8(AX), Y3
	VPBROADCASTD (SP), Y4
	VPSUBD       Y4, Y3, Y4
	VPMULLD      Y4, Y4, Y4
	VPXOR        Y5, Y5, Y5
	VMOVDQU      Y0, Y6
	VPBROADCASTD 4(SP), Y7
	VPSUBD       Y7, Y3, Y7
	VPMULLD      Y7, Y7, Y7
	VPCMPGTD     Y7, Y4, Y8
	VPBLENDVB    Y8, Y7, Y4, Y4
	VPBLENDVB    Y8, Y6, Y5, Y5
	VPADDD       Y0, Y6, Y6
	VPBROADCASTD 8(SP), Y7
	VPSUBD       Y7, Y3, Y7
	VPMULLD      Y7, Y7, Y7
	VPCMPGTD     Y7, Y4, Y8
	VPBLENDVB    Y8, Y7, Y4, Y4
	VPBLENDVB    Y8, Y6, Y5, Y5
	VPADDD       Y0, Y6, Y6
	VPBROADCASTD 12(SP), Y7
	VPSUBD       Y7, Y3, Y7
	VPMULLD      Y7, Y7, Y7
	VPCMPGTD     Y7, Y4, Y8
	VPBLENDVB    Y8, Y7, Y4, Y4
	VPBLENDVB    Y8, Y6, Y5, Y5
	VPADDD       Y0, Y6, Y6
	VPBROADCASTD 16(SP), Y7
	VPSUBD       Y7, Y3, Y7
	VPMULLD      Y7, Y7, Y7
	VPCMPGTD     Y7, Y4, Y8
	VPBLENDVB    Y8, Y7, Y4, Y4
	VPBLENDVB    Y8, Y6, Y5, Y5
	VPADDD       Y0, Y6, Y6
	VPBROADCASTD 20(SP), Y7
	VPSUBD       Y7, Y3, Y7
	VPMULLD      Y7, Y7, Y7
	VPCMPGTD     Y7, Y4, Y8
	VPBLENDVB    Y8, Y7, Y4, Y4
	VPBLENDVB    Y8, Y6, Y5, Y5
	VPADDD       Y0, Y6, Y6
	VPBROADCASTD 24(SP), Y7
	VPSUBD       Y7, Y3, Y7
	VPMULLD      Y7, Y7, Y7
	VPCMPGTD     Y7, Y4, Y8
	VPBLENDVB    Y8, Y7, Y4, Y4
	VPBLENDVB    Y8, Y6, Y5, Y5
	VPADDD       Y0, Y6, Y6
	VPBROADCASTD 28(SP), Y7
	VPSUBD       Y7, Y3, Y7
	VPMULLD      Y7, Y7, Y7
	VPCMPGTD     Y7, Y4, Y8
	VPBLENDVB    Y8, Y7, Y4, Y4
	VPBLENDVB    Y8, Y6, Y5, Y5
	VPSUBD       Y0, Y5, Y4
	VPCMPEQD     Y1, Y5, Y6
	VPBLENDVB    Y6, Y1, Y4, Y4
	VPCMPEQD     Y0, Y5, Y0
	VPBLENDVB    Y0, Y2, Y4, Y4
	VPSUBD       Y4, Y2, Y0
	VMOVDQU      Y0, Y1
	VPMULLD      Y0, Y1, Y1
	VEXTRACTI128 $0x01, Y1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0x4e, X1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0xe5, X1, X2
	VPADDD       X2, X1, X1
	VMOVD        X1, AX
	ADDL         AX, (DX)
	VMOVDQU      Y4, Y1
	VPMULLD      Y4, Y1, Y1
	VEXTRACTI128 $0x01, Y1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0x4e, X1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0xe5, X1, X2
	VPADDD       X2, X1, X1
	VMOVD        X1, AX
	ADDL         AX, 4(DX)
	VMOVDQU      Y0, Y1
	VPMULLD      Y4, Y1, Y1
	VEXTRACTI128 $0x01, Y1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0x4e, X1, X2
	VPADDD       X2, X1, X1
	VPSHUFD      $0xe5, X1, X2
	VPADDD       X2, X1, X1
	VMOVD        X1, AX
	ADDL         AX, 8(DX)
	VMOVDQU      Y0, Y0
	VPMULLD      Y3, Y0, Y0
	VEXTRACTI128 $0x01, Y0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0x4e, X0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0xe5, X0, X1
	VPADDD       X1, X0, X0
	VMOVD        X0, AX
	ADDL         AX, 12(DX)
	VMOVDQU      Y4, Y0
	VPMULLD      Y3, Y0, Y0
	VEXTRACTI128 $0x01, Y0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0x4e, X0, X1
	VPADDD       X1, X0, X0
	VPSHUFD      $0xe5, X0, X1
	VPADDD       X1, X0, X0
	VMOVD        X0, AX
	ADDL         AX, 16(DX)
	VZEROUPPER
	RET
