// Code generated by command: go run gen.go -out ../kernels_amd64.s -stubs ../kernels_stubs_amd64.go -pkg simd. DO NOT EDIT.

//go:build amd64 && !purego

package simd

// FindMinMaxSSE2 computes per-channel min/max over 16 RGBA pixels.
// Returns min RGBA packed little-endian in the low 32 bits and max RGBA in the high 32 bits.
//
//go:noescape
func FindMinMaxSSE2(block *[64]byte) uint64

// DecodeDXT1RowAVX2 decodes n consecutive interior DXT1 blocks (8 bytes each)
// into dst as 4 NRGBA rows of 16 bytes spaced stride bytes apart.
//
//go:noescape
func DecodeDXT1RowAVX2(dst *byte, src *byte, n int, stride int)

// DecodeDXT3RowAVX2 decodes n consecutive interior DXT3 blocks (16 bytes each)
// into dst as 4 NRGBA rows of 16 bytes spaced stride bytes apart. Requires BMI2.
//
//go:noescape
func DecodeDXT3RowAVX2(dst *byte, src *byte, n int, stride int)

// DecodeDXT5RowAVX2 decodes n consecutive interior DXT5 blocks (16 bytes each)
// into dst as 4 NRGBA rows of 16 bytes spaced stride bytes apart. Requires BMI2.
//
//go:noescape
func DecodeDXT5RowAVX2(dst *byte, src *byte, n int, stride int)

// DecodeBC4RowAVX2 decodes n consecutive interior BC4 blocks (8 bytes each)
// into dst as 4 gray NRGBA rows spaced stride bytes apart. Requires BMI2.
//
//go:noescape
func DecodeBC4RowAVX2(dst *byte, src *byte, n int, stride int)

// DecodeBC5RowAVX2 decodes n consecutive interior BC5 blocks (16 bytes each)
// into dst as 4 NRGBA rows (R, G, 0, 255) spaced stride bytes apart. Requires BMI2.
//
//go:noescape
func DecodeBC5RowAVX2(dst *byte, src *byte, n int, stride int)

// PackDXT1IndicesAVX2 maps 16 NRGBA pixels to weighted-SSE-nearest palette
// entries and packs the 2-bit indices. Alpha mode is driven by the params
// block: a sub-threshold pixel is forced to index 3 and the entry-3 penalty
// keeps that entry from winning the argmin. Ties keep the lowest index.
//
//go:noescape
func PackDXT1IndicesAVX2(block *[64]byte, params *[20]int32) uint32

// ScoreDXT1PaletteAVX2 returns the total weighted block error of one BC1
// endpoint pair (cc = c0 | c1<<16) over 16 pixels, palette built like the
// Go encoder. Used to drive endpoint refinement.
//
//go:noescape
func ScoreDXT1PaletteAVX2(block *[64]byte, cc uint32, weights *[4]int32) uint32

// AlphaBlockErrorAVX2 returns the summed minimum squared error of 16 alpha
// samples against the palette of endpoints aa = a0 | a1<<8 (BC3/BC4 scoring).
//
//go:noescape
func AlphaBlockErrorAVX2(samples *[16]uint8, aa uint32) uint32

// BestAlphaIndices16AVX2 returns the packed 48-bit BC3/BC4 alpha indices
// for 16 samples against the palette of endpoints aa = a0 | a1<<8.
// Ties keep the lowest index.
//
//go:noescape
func BestAlphaIndices16AVX2(samples *[16]uint8, aa uint32) uint64

// LSQColorAccumulateAVX2 assigns BC1 palette indices
// and accumulates least-squares normal-equation sums for 16 RGBA pixels.
//
//go:noescape
func LSQColorAccumulateAVX2(block *[64]byte, params *[22]int32, out *[9]int32)

// LSQAlphaAccumulateAVX2 assigns BC3/BC4 alpha indices
// and accumulates least-squares normal-equation sums for 16 samples.
//
//go:noescape
func LSQAlphaAccumulateAVX2(samples *[16]uint8, aa uint32, out *[5]int32)
